import {randomUUID} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import {ApplicationError,conflict,notFound} from '../application/errors';
import {siteImages} from '../frontend/assets/media';
import type {CmsRepository} from './repository';
import type {CmsAuditActor,CmsDocument,CmsEntity,CmsKind,CmsPublishedDocument,CmsRevision,CmsRevisionMutation,CmsRoute,CmsSeed,CmsSnapshot,CmsUnpublishInput} from './model';
import {assertCmsRoutePath,cmsKeySchema,cmsPathSchema,pathForContent,validateCmsContent} from './validation';

type Queryable=Pick<PoolClient,'query'>;
interface EntityRow {id:string;key:string;kind:CmsKind;row_version:number;draft_revision_id:string;published_revision_id:string|null}
interface RevisionRow {id:string;entity_id:string;revision_number:number;content:CmsDocument;created_at:Date|string;actor:string;source_revision_id:string|null}
const revisionDto=(row:RevisionRow):CmsRevision=>({id:row.id,revisionNumber:row.revision_number,content:row.content,createdAt:new Date(row.created_at).toISOString(),actor:row.actor,sourceRevisionId:row.source_revision_id});
async function find(c:Queryable,id:string,lock=false):Promise<EntityRow|null>{return(await c.query<EntityRow>(`SELECT id,key,kind,row_version,draft_revision_id,published_revision_id FROM cms_entities WHERE id=$1${lock?' FOR UPDATE':''}`,[id])).rows[0]??null;}
async function revision(c:Queryable,entityId:string,id:string):Promise<RevisionRow>{const row=(await c.query<RevisionRow>('SELECT * FROM cms_revisions WHERE entity_id=$1 AND id=$2',[entityId,id])).rows[0];if(!row)notFound('Revision does not belong to this item');return row;}
async function dto(c:Queryable,row:EntityRow):Promise<CmsEntity>{const draft=revisionDto(await revision(c,row.id,row.draft_revision_id));return{id:row.id,key:row.key,kind:row.kind,rowVersion:row.row_version,draftRevisionId:row.draft_revision_id,publishedRevisionId:row.published_revision_id,draft,published:row.published_revision_id?(row.published_revision_id===draft.id?draft:revisionDto(await revision(c,row.id,row.published_revision_id))):null};}
function expected(row:EntityRow|null,version:number):asserts row is EntityRow{if(!row)notFound();if(row.row_version!==version)conflict();}
async function audit(c:Queryable,row:EntityRow,actor:CmsAuditActor,action:string,fields:string[]):Promise<void>{await c.query(`INSERT INTO audit_events(actor_subject,actor_role,action,entity_type,entity_id,changed_fields,request_correlation_id) VALUES($1,$2,$3,'cms_entity',$4,$5::jsonb,$6)`,[actor.subject,actor.role,`cms.${action}`,row.id,JSON.stringify(fields),actor.correlationId]);}
async function availablePath(c:Queryable,id:string,kind:CmsKind,content:CmsDocument):Promise<void>{if(typeof content.id==='string'){const collision=(await c.query("SELECT 1 FROM cms_entities e JOIN cms_revisions r ON r.id=e.draft_revision_id WHERE e.id<>$1 AND e.kind=$2 AND r.content->>'id'=$3 LIMIT 1",[id,kind,content.id])).rowCount;if(collision)throw new ApplicationError(409,'identity_in_use','Another item owns this stable identity');}const path=pathForContent(kind,content);if(path===null)return;assertCmsRoutePath(kind,path);const collision=await c.query(`SELECT 1 FROM cms_entities e JOIN cms_revisions r ON r.id=e.draft_revision_id WHERE e.id<>$1 AND (r.content->>'path'=$2 OR(e.kind='home' AND $2='/')) UNION ALL SELECT 1 FROM cms_routes WHERE path=$2 AND entity_id<>$1 LIMIT 1`,[id,path]);if(collision.rowCount)throw new ApplicationError(409,'path_in_use','Another page owns this address');}
async function publishRoutes(c:Queryable,row:EntityRow,content:CmsDocument):Promise<void>{
 const path=pathForContent(row.kind,content);if(path===null)return;
 await availablePath(c,row.id,row.kind,content);
 const old=(await c.query<{path:string}>('SELECT path FROM cms_routes WHERE entity_id=$1 AND status=200 FOR UPDATE',[row.id])).rows[0]?.path;
 // A restored address can already be an alias. It becomes canonical below and
 // must not briefly point to itself while the remaining aliases are flattened.
 if(old&&old!==path)await c.query('UPDATE cms_routes SET target_path=$2,updated_at=now() WHERE status=301 AND target_path=$1 AND path<>$2',[old,path]);
 await c.query('UPDATE cms_routes SET status=301,target_path=$2,updated_at=now() WHERE entity_id=$1 AND path<>$2',[row.id,path]);
 await c.query(`INSERT INTO cms_routes(path,entity_id,status) VALUES($1,$2,200) ON CONFLICT(path) DO UPDATE SET status=200,target_path=NULL,updated_at=now() WHERE cms_routes.entity_id=EXCLUDED.entity_id`,[path,row.id]);
 for(const legacy of Array.isArray(content.legacyPaths)?content.legacyPaths:[]){if(typeof legacy!=='string'||legacy===path)continue;const collision=(await c.query(`SELECT 1 FROM cms_routes WHERE path=$1 AND entity_id<>$2 UNION ALL SELECT 1 FROM cms_entities e JOIN cms_revisions r ON r.id=e.draft_revision_id WHERE e.id<>$2 AND (r.content->>'path'=$1 OR(e.kind='home' AND $1='/')) LIMIT 1`,[legacy,row.id])).rowCount;if(collision)throw new ApplicationError(409,'legacy_path_in_use','Another page owns a legacy address');await c.query(`INSERT INTO cms_routes(path,entity_id,status,target_path) VALUES($1,$2,301,$3) ON CONFLICT(path) DO UPDATE SET status=301,target_path=EXCLUDED.target_path,updated_at=now() WHERE cms_routes.entity_id=EXCLUDED.entity_id`,[legacy,row.id,path]);}
}
async function appendRevision(c:Queryable,row:EntityRow,content:CmsDocument,actor:string,source:string|null):Promise<string>{const id=randomUUID();await c.query(`INSERT INTO cms_revisions(id,entity_id,revision_number,content,actor,source_revision_id) SELECT $1,$2,COALESCE(MAX(revision_number),0)+1,$3::jsonb,$4,$5 FROM cms_revisions WHERE entity_id=$2`,[id,row.id,JSON.stringify(content),actor,source]);await c.query('UPDATE cms_entities SET draft_revision_id=$2,row_version=row_version+1,updated_at=now() WHERE id=$1',[row.id,id]);return id;}
function mapSnapshot(rows:Array<EntityRow&{revision:RevisionRow;initial_metadata?:{title:string;heading:string;seeded:boolean}|null;editorial_modified_at?:Date|string|null}>,routes:CmsRoute[]):CmsSnapshot {const entities:CmsPublishedDocument[]=rows.map(row=>({id:row.id,key:row.key,kind:row.kind,revisionId:row.revision.id,...(row.initial_metadata?{initialMetadata:row.initial_metadata}:{}),...(row.editorial_modified_at?{modifiedAt:new Date(row.editorial_modified_at).toISOString()}:{}),content:row.revision.content,payload:row.revision.content}));return{entities,documents:Object.fromEntries(entities.map(row=>[row.key,row.content])),routes};}
export class PostgresCmsRepository implements CmsRepository {
 constructor(private readonly pool:Pool){}
 private async transaction<T>(run:(c:PoolClient)=>Promise<T>,readOnly=false):Promise<T>{const c=await this.pool.connect();try{await c.query(readOnly?'BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY':'BEGIN');if(!readOnly){await c.query("SET LOCAL savinggrace.application_request='on'");await c.query('SELECT pg_advisory_xact_lock(179,27)');}const result=await run(c);await c.query('COMMIT');return result;}catch(error){await c.query('ROLLBACK');if((error as {code?:string}).code==='23505')throw new ApplicationError(409,'already_exists','This item or address already exists');throw error;}finally{c.release();}}
 async list():Promise<CmsEntity[]>{return this.transaction(async c=>{const rows=(await c.query<EntityRow>('SELECT * FROM cms_entities ORDER BY kind,key')).rows;return Promise.all(rows.map(row=>dto(c,row)));},true);}
 async get(id:string):Promise<CmsEntity|null>{return this.transaction(async c=>{const row=await find(c,id);return row?dto(c,row):null;},true);}
 async history(id:string):Promise<CmsRevision[]>{return this.transaction(async c=>{if(!await find(c,id))notFound();return(await c.query<RevisionRow>('SELECT * FROM cms_revisions WHERE entity_id=$1 ORDER BY revision_number DESC',[id])).rows.map(revisionDto);},true);}
 async create(input:{key:string;kind:CmsKind;content:CmsDocument},actor:CmsAuditActor):Promise<CmsEntity>{cmsKeySchema.parse(input.key);const content=validateCmsContent(input.kind,input.content);return this.transaction(async c=>{const entityId=randomUUID(),revisionId=randomUUID();await availablePath(c,entityId,input.kind,content);await c.query('INSERT INTO cms_entities(id,key,kind,draft_revision_id) VALUES($1,$2,$3,$4)',[entityId,input.key,input.kind,revisionId]);await c.query('INSERT INTO cms_revisions(id,entity_id,revision_number,content,actor) VALUES($1,$2,1,$3::jsonb,$4)',[revisionId,entityId,JSON.stringify(content),actor.subject]);const row=(await find(c,entityId))!;await audit(c,row,actor,'create',['draft']);return dto(c,row);});}
 async save(id:string,input:{expectedRowVersion:number;content:CmsDocument},actor:CmsAuditActor):Promise<CmsEntity>{return this.transaction(async c=>{const row=await find(c,id,true);expected(row,input.expectedRowVersion);const content=validateCmsContent(row.kind,input.content);const previous=await revision(c,id,row.draft_revision_id);if(previous.content.id!==content.id)throw new ApplicationError(400,'immutable_identity','Stable content identity cannot change');await availablePath(c,id,row.kind,content);await appendRevision(c,row,content,actor.subject,null);await audit(c,row,actor,'save',['draft']);return dto(c,(await find(c,id))!);});}
 async publish(id:string,input:CmsRevisionMutation,actor:CmsAuditActor):Promise<CmsEntity>{return this.transaction(async c=>{const row=await find(c,id,true);expected(row,input.expectedRowVersion);if(row.draft_revision_id!==input.revisionId)conflict('Publish the current draft revision');const selected=await revision(c,id,input.revisionId);const content=validateCmsContent(row.kind,selected.content);await publishRoutes(c,row,content);await this.validateReferences(c,row,content);await c.query('UPDATE cms_entities SET published_revision_id=$2,row_version=row_version+1,updated_at=now() WHERE id=$1',[id,input.revisionId]);await audit(c,row,actor,'publish',['publishedRevision','routes']);return dto(c,(await find(c,id))!);});}
 async unpublish(id:string,input:CmsUnpublishInput,actor:CmsAuditActor):Promise<CmsEntity>{return this.transaction(async c=>{const row=await find(c,id,true);expected(row,input.expectedRowVersion);if(['home','settings','navigation'].includes(row.kind))throw new ApplicationError(400,'required_site_content','Use visibility controls for required site settings');if(!row.published_revision_id)throw new ApplicationError(409,'not_published','This item is already unpublished');if(row.kind==='venue'){const selected=await revision(c,id,row.published_revision_id);const used=(await c.query("SELECT 1 FROM cms_entities e JOIN cms_revisions r ON r.id=e.published_revision_id WHERE e.kind='event' AND r.content->>'venue'=$1 LIMIT 1",[selected.content.id])).rowCount;if(used)throw new ApplicationError(409,'venue_in_use','Move or unpublish events using this venue first');}let target:string|null=null;if(input.disposition==='redirect'){target=cmsPathSchema.parse(input.targetPath);const targetRow=(await c.query<{entity_id:string}>("SELECT r.entity_id FROM cms_routes r JOIN cms_entities e ON e.id=r.entity_id JOIN cms_revisions v ON v.id=e.published_revision_id WHERE r.path=$1 AND r.status=200 AND COALESCE(v.content->'seo'->>'noindex','false')<>'true'",[target])).rows[0];if(!targetRow||targetRow.entity_id===id)throw new ApplicationError(400,'invalid_redirect','Choose another published, indexable page');}else await this.assertNoIncomingLinks(c,row);const current=(await c.query<{path:string}>('SELECT path FROM cms_routes WHERE entity_id=$1 AND status=200',[id])).rows[0]?.path;if(current)await c.query('UPDATE cms_routes SET status=$2,target_path=$3,updated_at=now() WHERE status=301 AND target_path=$1',[current,target?301:410,target]);await c.query('UPDATE cms_routes SET status=$2,target_path=$3,updated_at=now() WHERE entity_id=$1',[id,target?301:410,target]);await c.query('UPDATE cms_entities SET published_revision_id=NULL,row_version=row_version+1,updated_at=now() WHERE id=$1',[id]);await audit(c,row,actor,'unpublish',['publishedRevision','routes']);return dto(c,(await find(c,id))!);});}
 async restore(id:string,input:CmsRevisionMutation,actor:CmsAuditActor):Promise<CmsEntity>{return this.transaction(async c=>{const row=await find(c,id,true);expected(row,input.expectedRowVersion);const selected=await revision(c,id,input.revisionId);const content=validateCmsContent(row.kind,selected.content);await availablePath(c,id,row.kind,content);await appendRevision(c,row,content,actor.subject,selected.id);await audit(c,row,actor,'restore',['draft']);return dto(c,(await find(c,id))!);});}
 async seed(seeds:readonly CmsSeed[],subject='cms-initializer'):Promise<{inserted:number;unchanged:number}>{const values=seeds.map(seed=>({...seed,content:validateCmsContent(seed.kind,seed.payload)}));return this.transaction(async c=>{let inserted=0,unchanged=0;const rows:Array<{row:EntityRow;content:CmsDocument;publish:boolean}>=[];for(const seed of values){cmsKeySchema.parse(seed.key);const entityId=randomUUID(),revisionId=randomUUID();const created=await c.query('INSERT INTO cms_entities(id,key,kind,draft_revision_id,published_revision_id,seed_key) VALUES($1,$2,$3,$4,$5,$2) ON CONFLICT(key) DO NOTHING RETURNING id',[entityId,seed.key,seed.kind,revisionId,seed.publish?revisionId:null]);if(!created.rowCount){unchanged++;continue;}await c.query('INSERT INTO cms_revisions(id,entity_id,revision_number,content,actor) VALUES($1,$2,1,$3::jsonb,$4)',[revisionId,entityId,JSON.stringify(seed.content),subject]);const row=(await find(c,entityId))!;rows.push({row,content:seed.content,publish:seed.publish});await audit(c,row,{subject,role:'system',correlationId:'cms-initialization'},'initialize',['draft',...(seed.publish?['publishedRevision']:[])]);inserted++;}for(const {row,content,publish}of rows)if(publish)await publishRoutes(c,row,content);return{inserted,unchanged};});}
 private async snapshot(c:Queryable):Promise<CmsSnapshot>{const rows=(await c.query<EntityRow&{revision:RevisionRow}>(`SELECT e.*,to_jsonb(r) AS revision,(SELECT jsonb_build_object('title',first.content->>'title','heading',COALESCE(first.content->>'heading',first.content->>'title'),'seeded',e.seed_key IS NOT NULL) FROM cms_revisions first WHERE first.entity_id=e.id ORDER BY first.revision_number LIMIT 1) AS initial_metadata,CASE WHEN r.revision_number>1 AND r.source_revision_id IS NULL AND r.content IS DISTINCT FROM(SELECT prior.content FROM cms_revisions prior WHERE prior.entity_id=e.id AND prior.revision_number<r.revision_number ORDER BY prior.revision_number DESC LIMIT 1) THEN r.created_at ELSE NULL END AS editorial_modified_at FROM cms_entities e JOIN cms_revisions r ON r.id=e.published_revision_id ORDER BY e.key`)).rows;const routes=(await c.query<CmsRoute>('SELECT path,entity_id AS "entityId",status,target_path AS "targetPath" FROM cms_routes ORDER BY path')).rows;return mapSnapshot(rows,routes);}
 async getPublishedSnapshot():Promise<CmsSnapshot>{return this.transaction(c=>this.snapshot(c),true);}
 async getPreviewSnapshot(selection:{entityId:string;revisionId?:string}):Promise<CmsSnapshot>{return this.transaction(async c=>{const row=await find(c,selection.entityId);if(!row)notFound();const selected=await revision(c,row.id,selection.revisionId??row.draft_revision_id);const snapshot=await this.snapshot(c);const initialMetadata=snapshot.entities.find(item=>item.id===row.id)?.initialMetadata;snapshot.entities=snapshot.entities.filter(item=>item.id!==row.id);snapshot.entities.push({...(initialMetadata?{initialMetadata}:{}),id:row.id,key:row.key,kind:row.kind,revisionId:selected.id,content:selected.content,payload:selected.content});snapshot.documents[row.key]=selected.content;const path=pathForContent(row.kind,selected.content);snapshot.routes=snapshot.routes.filter(route=>route.entityId!==row.id);if(path)snapshot.routes.push({path,entityId:row.id,status:200,targetPath:null});return snapshot;},true);}
 async canReadAsset(storageKey:string,draft:boolean):Promise<boolean>{if(!/^[a-f0-9]{64}\.(?:png|jpg|jpeg|webp|gif|pdf)$/u.test(storageKey))return false;return this.transaction(async c=>{const rows=(await c.query<{content:unknown}>(`SELECT r.content FROM cms_entities e JOIN cms_revisions r ON r.id=e.${draft?'draft_revision_id':'published_revision_id'}`)).rows;const assetId=(await c.query<{id:string}>("SELECT id FROM media_assets WHERE storage_provider='cms_local' AND storage_key=$1 AND availability_status='available'",[storageKey])).rows[0]?.id;const refs=new Set([...(assetId?[assetId]:[]),storageKey,`/cms-assets/${storageKey}`]);function contains(value:unknown):boolean{return typeof value==='string'?[...refs].some(ref=>value===ref||value.includes(`](${ref})`)):value!==null&&typeof value==='object'&&Object.values(value).some(contains);}return rows.some(row=>contains(row.content));},true);}
 private async assertNoIncomingLinks(c:Queryable,row:EntityRow):Promise<void>{
  const owned=new Set((await c.query<{path:string}>('SELECT path FROM cms_routes WHERE entity_id=$1 OR(status=301 AND target_path IN(SELECT path FROM cms_routes WHERE entity_id=$1 AND status=200))',[row.id])).rows.map(item=>item.path));
  const documents=(await c.query<{content:CmsDocument}>("SELECT r.content FROM cms_entities e JOIN cms_revisions r ON r.id=e.published_revision_id WHERE e.id<>$1",[row.id])).rows;
  const pointsHere=(href:string)=>{const path=href.split(/[?#]/u)[0]!;return owned.has(path)||owned.has(path+'/');};
  const contains=(value:unknown,key=''):boolean=>{
   if(typeof value==='string')return (/href$/iu.test(key)&&pointsHere(value))||[...value.matchAll(/\[[^\]]*\]\((\/[^)]*)\)/gu)].some(match=>pointsHere(match[1]!));
   if(!value||typeof value!=='object'||('enabled'in value&&value.enabled===false))return false;
   return Object.entries(value).some(([childKey,child])=>contains(child,childKey));
  };
  if(documents.some(document=>contains(document.content)))throw new ApplicationError(409,'page_in_use','Update published links to this page, or choose an equivalent redirect destination before removing it');
 }
 private async validateReferences(c:Queryable,row:EntityRow,content:CmsDocument):Promise<void>{
  const published=async(kind:string,id:unknown)=>Boolean((await c.query(`SELECT 1 FROM cms_entities e JOIN cms_revisions r ON r.id=e.published_revision_id WHERE e.kind=$1 AND r.content->>'id'=$2`,[kind,id])).rowCount);
  if(row.kind==='event'&&!await published('venue',content.venue))throw new ApplicationError(400,'unpublished_venue','Publish the event venue first');
  for(const related of [content.parent,content.page,...(Array.isArray(content.related)?content.related:[])])if(related&&!await published('page',related))throw new ApplicationError(400,'unpublished_page','A related or parent page is not published');
  const assets=new Set<string>(),imageIds=new Set<string>(),eventIds=new Set<string>(),links=new Set<string>();
  function visit(value:unknown,key=''):void{
   if(typeof value==='string'){
    for(const match of value.matchAll(/\/cms-assets\/([a-f0-9]{64}\.(?:png|jpg|jpeg|webp|gif|pdf))/gu))assets.add(match[1]!);
    if(['image','media','logoAsset','footerLogoAsset','faviconAsset','touchIconAsset'].includes(key)&&value)imageIds.add(value);
    if(key==='event')eventIds.add(value);
    if(/href$/iu.test(key)&&value.startsWith('/'))links.add(value.split(/[?#]/u)[0]!);
    for(const match of value.matchAll(/\[[^\]]*\]\((\/[^)]*)\)/gu))links.add(match[1]!.split(/[?#]/u)[0]!);
   }else if(value&&typeof value==='object'&&(!('enabled'in value)||value.enabled!==false))for(const [childKey,child]of Object.entries(value))visit(child,childKey);
  }
  visit(content);
  for(const event of eventIds)if(!await published('event',event))throw new ApplicationError(400,'unpublished_event','Choose a published gathering');
  for(const key of assets){const available=(await c.query("SELECT 1 FROM media_assets WHERE storage_provider='cms_local' AND storage_key=$1 AND availability_status='available'",[key])).rowCount;if(!available)throw new ApplicationError(400,'missing_asset','A selected upload is unavailable');}
  const embedded=new Set([...siteImages.map(image=>image.id),'church-logo']);
  for(const id of imageIds){
   if(embedded.has(id))continue;
   const byPath=/^\/cms-assets\/(.+)$/u.exec(id);
   const isUuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/iu.test(id);
   if(!byPath&&!isUuid)throw new ApplicationError(400,'missing_asset','Choose an available image');
   const available=(await c.query(`SELECT 1 FROM media_assets WHERE ${byPath?'storage_key=$1 AND storage_provider=\'cms_local\'':'id=$1::uuid'} AND availability_status='available' AND content_type IN('image/jpeg','image/png','image/webp','image/gif')`,[byPath?byPath[1]:id])).rowCount;
   if(!available)throw new ApplicationError(400,'invalid_image','Choose an available image; documents cannot be used as images');
  }
  const current=pathForContent(row.kind,content);
  for(const link of links){
   if(link===current||/^\/(?:sermons(?:-v[145])?|speakers|series|books)(?:\/|$)/u.test(link)||link==='/events/calendar.ics'||link.startsWith('/cms-assets/')||link.startsWith('/media/')||link.startsWith('/brand/'))continue;
   const found=(await c.query('SELECT 1 FROM cms_routes r LEFT JOIN cms_routes target ON target.path=r.target_path WHERE r.path=$1 AND (r.status=200 OR(r.status=301 AND target.status=200))',[link])).rowCount;
   if(!found)throw new ApplicationError(400,'unpublished_link','An internal link does not lead to a published page');
  }
 }
}
