import {createHash} from 'node:crypto';
import {normalizeSermonAudio} from '../domain/media';
import {youtubeVideoIdFromUrl, youtubeVideoIdPattern} from '../domain/youtube';
import {matchSourceRecording, officialChurchBroadcasterId, type SourceMediaEvidence} from '../metadata/sermonaudio-matching';

export const sha256 = (bytes: string | Uint8Array): string => createHash('sha256').update(bytes).digest('hex');
export const authorizedTranscriptManifestSha256='a4fa3627682043c4b06aa65ddbebdab75f1fc29aec93e2d250bda537d9b0cd2b';
export function assertAuthorizedTranscriptManifest(bytes:Uint8Array):void {
  if(sha256(bytes)!==authorizedTranscriptManifestSha256)throw new SafeRetrievalError('authorized_manifest_hash_conflict');
}
export interface WordPressTranscriptSource extends SourceMediaEvidence {
  status: string;
  sourceModifiedAt: string | null;
  youtubeValues: string[];
  videoEmbedValues: string[];
}
export interface RecordingTranscriptMetadata {
  sermonID: string;
  fullTitle: string;
  preachDate: string | null;
  languageCode: string;
  languageCode3: string;
  hasAudio: boolean;
  updateDate: number | null;
  broadcaster: {broadcasterID: string};
  speaker: {displayName: string};
  transcript: {language: string | null; downloadURL: string | null; approveTimestamp: number | null; autoGenerated: boolean} | null;
}
export function hasValidYouTube(source: WordPressTranscriptSource): boolean {
  if(source.youtubeValues.some(v => youtubeVideoIdPattern.test(v.trim()) || youtubeVideoIdFromUrl(v))) return true;
  return source.videoEmbedValues.some(value => {
    if(/<script\b/i.test(value) || (value.match(/<iframe\b/gi)??[]).length !== 1) return false;
    const url = /<iframe\b[^>]*\ssrc\s*=\s*(["'])(.*?)\1/i.exec(value)?.[2];
    return Boolean(url && youtubeVideoIdFromUrl(url.replaceAll('&amp;', '&')));
  });
}
export function inventoryCandidate(source: WordPressTranscriptSource): {eligible: boolean; reason: string; recordingId?: string} {
  if(!['publish','pending'].includes(source.status) || !source.title.trim()) return {eligible:false,reason:'source_status_or_title_ineligible'};
  if(hasValidYouTube(source)) return {eligible:false,reason:'valid_youtube_mapping_present'};
  const ids=[...new Set(source.audioValues.map(value=>normalizeSermonAudio(value, source.title)?.media.externalId).filter((id): id is string=>Boolean(id)))];
  if(ids.length>1) return {eligible:false,reason:'conflicting_explicit_recordings'};
  if(!ids.length) return {eligible:false,reason:'explicit_sermonaudio_identity_unavailable'};
  return {eligible:true,reason:'requires_official_recording_verification',recordingId:ids[0]!};
}
export function verifyRecording(source: WordPressTranscriptSource, metadata: RecordingTranscriptMetadata): {valid:boolean; reason:string} {
  const candidate=inventoryCandidate(source);
  if(!candidate.eligible || metadata.sermonID!==candidate.recordingId) return {valid:false,reason:'exact_recording_identity_mismatch'};
  const match=matchSourceRecording({sourceWordPressId:source.sourceWordPressId,title:source.title,serviceDate:source.serviceDate,speaker:source.speakerNames.length===1?source.speakerNames[0]!:null},source,[{
    id:metadata.sermonID,title:metadata.fullTitle,speaker:metadata.speaker?.displayName??'',broadcasterId:metadata.broadcaster?.broadcasterID??null,
    hasAudio:metadata.hasAudio,serviceDate:metadata.preachDate
  }]);
  if(match.outcome!=='verified') return {valid:false,reason:match.reason};
  // A copied link to another sermon by the same preacher on the same day must
  // not pass merely because speaker/date match. Require corroborated title too.
  if(!metadata.preachDate || !match.corroboration?.title) return {valid:false,reason:'title_or_preached_date_not_corroborated'};
  if(source.speakerNames.length>1 || (source.speakerNames.length===1 && !match.corroboration.speaker)) return {valid:false,reason:'source_speaker_conflict'};
  return {valid:true,reason:'exact_source_recording_broadcaster_title_date_and_available_speaker'};
}
export function verifyBroadcaster(value: unknown): boolean {
  if(!value || typeof value!=='object') return false;
  const b=value as Record<string,unknown>;
  return b.broadcasterID===officialChurchBroadcasterId && typeof b.displayName==='string' && /Saving Grace Bible Church/i.test(b.displayName) && typeof b.address==='string' && /Westmeadows/i.test(b.address);
}
export function transcriptDownloadUrl(value: string): URL {
  const u=new URL(value);
  // This is the exact official host observed in TranscriptMedia.downloadURL.
  // No arbitrary host, port, credentials, media stream or guessed endpoint.
  if(u.protocol!=='https:' || u.hostname!=='cloud.sermonaudio.com' || u.port || u.username || u.password || u.hash || !u.pathname.endsWith('.transcript')) throw Error('transcript_download_url_rejected');
  if([...u.searchParams.keys()].some(k=>/api.?key|token|auth|tlang|translat/i.test(k))) throw Error('transcript_download_url_rejected');
  return u;
}
export function originalLanguage(metadata: RecordingTranscriptMetadata): string | null {
  const language=metadata.transcript?.language?.toLowerCase();
  if(!language) return null;
  return [metadata.languageCode.toLowerCase(), metadata.languageCode3.toLowerCase()].includes(language)?language:null;
}
export function inspectTranscriptBytes(bytes: Uint8Array): {valid:boolean; reason:string; words:number; characters:number; format:string} {
  const invalid=(reason:string)=>({valid:false,reason,words:0,characters:0,format:'unrecognized'});
  if(bytes.byteLength>20_000_000 || bytes.byteLength<200) return invalid('transcript_size_unusable');
  let text:string;
  try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{return invalid('transcript_utf8_invalid');}
  if(/<\s*(?:!doctype|html|script)|<Error\b/i.test(text) || /\u0000/.test(text)) return invalid('error_html_or_binary_response');
  let format='plain_text';
  if(/^\s*[\[{]/.test(text)) {
    try {
      const obj=JSON.parse(text);
      if(obj?.error || obj?.errors || obj?.detail || obj?.message) return invalid('error_json_response');
      // Only documented/observed text containers; never count JSON keys or a
      // search snippet/summary as a full transcript.
      if(typeof obj?.text==='string') text=obj.text;
      else if(Array.isArray(obj) && obj.every(v=>typeof v?.text==='string')) text=obj.map(v=>v.text).join('\n');
      else if(Array.isArray(obj?.segments) && obj.segments.every((v: unknown)=>Boolean(v && typeof (v as {text?:unknown}).text==='string'))) text=obj.segments.map((v:{text:string})=>v.text).join('\n');
      else return invalid('unsupported_transcript_json');
      format='json_text';
    }catch{return invalid('malformed_transcript_json');}
  }
  if(/^\s*(?:access denied|unauthorized|forbidden|not found|please (?:log|sign) in)\b/i.test(text)) return invalid('error_text_response');
  const words=text.match(/[\p{L}\p{N}]+(?:['’][\p{L}\p{N}]+)*/gu)?.length??0;
  if(words<30) return invalid('transcript_text_unusable');
  return {valid:true,reason:'full_original_download_text_usable',words,characters:text.length,format};
}

export class SafeRetrievalError extends Error {
  constructor(readonly classification:string, readonly httpStatus:number|null=null){super(classification);}
}
export type FetchFunction=(url:string, init:RequestInit)=>Promise<Response>;
export class SermonAudioReader {
  private lastRequest=0;
  constructor(private readonly key:string, private readonly fetcher:FetchFunction=fetch, private readonly delay:(ms:number)=>Promise<void>=ms=>new Promise(r=>setTimeout(r,ms)), private readonly spacingMs=1000, private readonly maxAttempts=3) {
    if(!key.trim() || /\s/.test(key.trim())) throw new SafeRetrievalError('credential_format_invalid');
    if(!Number.isInteger(maxAttempts)||maxAttempts<1||maxAttempts>3)throw new SafeRetrievalError('retry_limit_invalid');
  }
  async get(url:URL, authenticated:boolean):Promise<{bytes:Uint8Array;contentType:string;etag:string|null;lastModified:string|null}> {
    if(authenticated && (url.origin!=='https://api.sermonaudio.com' || !/^\/v2\/node\/(?:broadcasters\/savinggrace|sermons\/\d{1,24})$/.test(url.pathname) || url.search)) throw new SafeRetrievalError('api_request_scope_rejected');
    if(!authenticated) transcriptDownloadUrl(url.href);
    for(let attempt=0;attempt<this.maxAttempts;attempt++) {
      await this.delay(Math.max(0,this.lastRequest+this.spacingMs-Date.now()));this.lastRequest=Date.now();
      let r:Response;
      try {r=await this.fetcher(url.href,{method:'GET',headers:authenticated?{'X-Api-Key':this.key}:{},redirect:'manual',signal:AbortSignal.timeout(25000)});}catch{
        if(attempt===this.maxAttempts-1)throw new SafeRetrievalError('transport_failure');await this.delay(1000*2**attempt);continue;
      }
      if(r.status===401 || r.status===403) {await r.body?.cancel();throw new SafeRetrievalError('authentication_or_permission_failure',r.status);}
      if(r.status===429 || [500,502,503,504].includes(r.status)) {
        const header=r.headers.get('retry-after'); const seconds=header && /^\d+$/.test(header)?Number(header):null;
        const date=header && seconds===null?Date.parse(header):NaN;
        const wait=seconds!==null?seconds*1000:Number.isFinite(date)?Math.max(0,date-Date.now()):1000*2**attempt;
        await r.body?.cancel();
        if(attempt===this.maxAttempts-1 || wait>60000)throw new SafeRetrievalError(r.status===429?'rate_limited':'temporary_provider_failure',r.status);
        await this.delay(wait);continue;
      }
      if(!r.ok){await r.body?.cancel();throw new SafeRetrievalError(r.status>=300&&r.status<400?'redirect_refused':r.status===404?'resource_unavailable':'provider_response_failure',r.status);}
      const declared=Number(r.headers.get('content-length')??0);
      if(declared>20_000_000){await r.body?.cancel();throw new SafeRetrievalError('response_too_large');}
      const chunks:Uint8Array[]=[];let length=0;
      if(!r.body)throw new SafeRetrievalError('response_body_missing');
      const reader=r.body.getReader();
      try{for(;;){const part=await reader.read();if(part.done)break;length+=part.value.byteLength;if(length>20_000_000){await reader.cancel();throw new SafeRetrievalError('response_too_large');}chunks.push(part.value);}}
      catch(e){if(e instanceof SafeRetrievalError)throw e;await reader.cancel().catch(()=>{});if(attempt===this.maxAttempts-1)throw new SafeRetrievalError('response_body_transport_failure',r.status);await this.delay(1000*2**attempt);continue;}
      const bytes=new Uint8Array(length);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}
      const bounded=(value:string|null)=>value && value.length<256&&!/[\r\n]/.test(value)?value:null;
      return {bytes,contentType:r.headers.get('content-type')??'',etag:bounded(r.headers.get('etag')),lastModified:bounded(r.headers.get('last-modified'))};
    }
    throw new SafeRetrievalError('retry_exhausted');
  }
  async metadata<T>(path:string):Promise<{value:T;bytes:Uint8Array}> {
    const result=await this.get(new URL(path,'https://api.sermonaudio.com'),true);
    try{return {value:JSON.parse(new TextDecoder().decode(result.bytes)) as T,bytes:result.bytes};}catch{throw new SafeRetrievalError('metadata_json_invalid');}
  }
}
