import {sourceCmsPostgresLifecycle} from './helpers/source-cms-postgres-lifecycle';
import type {Pool} from 'pg';
import {expect,it} from 'vitest';
import {assertDisposableIntegrationTestDatabase} from '../src/migration/local-database-safety';
import {completedSchemaMigrations} from '../src/staging/completed-schema';
import {loadAcceptedSemanticMigration} from '../src/semantic/accepted-semantic-migration';
import {loadCmsMigration,verifyCmsSchema} from '../src/cms/migration';
import {loadSourcePublicMigration} from '../src/seo/source-public-migration';
import {applySourcePublicMigration,importSourcePublicBundle,readSourcePublicPages,restoreSourcePublicImport} from '../src/seo/source-public-store';
import {sourceBundleSchema,sourceVersionHash,type SourcePublicPage} from '../src/seo/source-public-model';
import {createCompositeSourceSermonRepository} from '../src/seo/composite-sermon-repository';
import {sourceRuntimeFingerprint} from '../src/seo/runtime-snapshot';
import {publicSermonListQuerySchema} from '../src/api/contracts/public-sermons';
function guard(){assertDisposableIntegrationTestDatabase(process.env.TEST_DATABASE_URL!,process.env.DISPOSABLE_TEST_DATABASE_TOKEN,process.env.ALLOW_LOCAL_DB_WRITE);}
const commit='a'.repeat(40),hash='b'.repeat(64);
function fixture():SourcePublicPage{return{path:'/anonymous-original/',kind:'page',sourceUrl:'https://www.savinggrace.org.au/anonymous-original/',sourceId:919191,capturedAt:'2026-10-09T00:00:00Z',responseSha256:hash,title:'Anonymous original page',heading:'Anonymous original page',description:null,language:'en',indexable:true,canonicalSource:'https://www.savinggrace.org.au/anonymous-original/',publishedAt:'2004-01-01T00:00:00Z',modifiedAt:null,content:[{tag:'p',text:'Anonymous original public wording.'}],links:[],mediaReferences:[],sermon:null,issues:[],passageTerms:[]};}
export function registerSeoSourcePostgresTests(getPool:()=>Pool){
 it('the source/editorial factory admits only normal approved publication and never resurrects a withdrawn original',async()=>{guard();const client=await getPool().connect();try{
  await client.query('BEGIN');const suffix=[...(await completedSchemaMigrations()).slice(22),await loadAcceptedSemanticMigration(),await loadCmsMigration()];for(const item of suffix){await client.query(item.upBody);await client.query('INSERT INTO schema_migrations(migration_order,migration_id,checksum_sha256) VALUES($1,$2,$3)',[item.order,item.id,item.checksumSha256]);}await applySourcePublicMigration(client);
  const ids=['9a100000-0000-4000-8000-000000000001','9a100000-0000-4000-8000-000000000002'],speaker='9a100000-0000-4000-8000-000000000003';
  await client.query("INSERT INTO speakers(id,name,slug) VALUES($1,'Anonymous composite speaker','anonymous-composite-speaker')",[speaker]);
  for(const [index,id]of ids.entries()){
   await client.query(`INSERT INTO sermons(id,title,slug,status,service_date,published_at,speaker_id,source_wordpress_id,summary,summary_status,summary_source_kind,summary_created_at,summary_updated_at)
    VALUES($1,'Imported anonymous title',$2,'published','2004-01-01',now(),$3,$4,$5,'draft','manual',now(),now())`,[id,index?'new-composite-fixture':'evaluation-composite-fixture',speaker,index?null:987991,'A synthetic compositefixturekeyword description supplies sufficient anonymous words for the normal public eligibility regression without real sermon material.']);
   await client.query("INSERT INTO sermon_transcripts(sermon_id,body_text,status,source_kind,reviewed_by_subject,approved_by_subject,reviewed_at,approved_at) VALUES($1,'Anonymous approved composite transcript.','approved','manual','fixture-admin','fixture-admin',now(),now())",[id]);
   for(let order=1;order<=5;order++)await client.query("INSERT INTO sermon_question_answers(sermon_id,question_text,answer_text,display_order,status,source_kind,reviewed_by_subject,approved_by_subject,reviewed_at,approved_at) VALUES($1,'An anonymous question?','An anonymous approved answer.',$2,'approved','manual','fixture-admin','fixture-admin',now(),now())",[id,order]);
   await client.query("INSERT INTO sermon_media(sermon_id,provider,media_type,external_id,canonical_url,title,is_primary,availability_status) VALUES($1,'youtube','video','Z0000000099','https://www.youtube.com/watch?v=Z0000000099','Anonymous fixture video',true,'available')",[id]);
   await client.query("INSERT INTO sermon_primary_passage_reviews(sermon_id,proposal_outcome,evidence_source,evidence_sha256,parser_version,review_status,reviewed_by_subject,reviewed_at) VALUES($1,'no_reference','administrator',$2,'anonymous-composite-v1','confirmed_none','fixture-admin',now())",[id,hash]);
  }
  const page:SourcePublicPage={...fixture(),path:'/sermons/original-composite-fixture/',kind:'sermon',sourceUrl:'https://www.savinggrace.org.au/sermons/original-composite-fixture/',sourceId:987991,canonicalSource:'https://www.savinggrace.org.au/sermons/original-composite-fixture/',sermon:{id:'9a100000-0000-4000-8000-000000000004',slug:'original-composite-fixture',title:'Original anonymous title',serviceDate:'2004-01-01',summary:null,speaker:null,series:[],books:[],scriptureReferences:[],primaryPassages:[],primaryPassageState:'unresolved',primaryMedia:null,seoDescription:null,body:'Original anonymous source body.',media:[],transcript:null,questionAnswers:[],relatedSermons:[]}};
  await importSourcePublicBundle(client,{format:'sgbc-source-public-v1',capturedAt:page.capturedAt,inventorySha256:hash,pages:[page],expectedVersions:{[page.path]:null}},commit);
  const build=async()=>createCompositeSourceSermonRepository(await readSourcePublicPages(client),client);
  let repository=await build();expect((await repository.findPublishedBySlug('original-composite-fixture'))?.summary).toBeNull();expect(await repository.findPublishedBySlug('new-composite-fixture')).toBeNull();
  await client.query("UPDATE sermons SET summary_status='approved',summary_reviewed_by_subject='fixture-admin',summary_approved_by_subject='fixture-admin',summary_reviewed_at=now(),summary_approved_at=now() WHERE id=ANY($1::uuid[])",[ids]);
  repository=await build();expect((await repository.findPublishedBySlug('original-composite-fixture'))?.summary).toContain('compositefixturekeyword');expect((await repository.findPublishedBySlug('original-composite-fixture'))?.title).toBe('Original anonymous title');expect(await repository.findPublishedBySlug('evaluation-composite-fixture')).toBeNull();expect(await repository.findPublishedBySlug('new-composite-fixture')).not.toBeNull();expect((await repository.listPublished(publicSermonListQuerySchema.parse({query:'compositefixturekeyword'}))).data.map(item=>item.id)).toEqual(expect.arrayContaining(ids));
  await client.query("UPDATE sermons SET title='Explicit anonymous title',slug='final-composite-fixture' WHERE id=$1",[ids[0]]);
  await client.query("INSERT INTO audit_events(actor_subject,actor_role,action,entity_type,entity_id,changed_fields,request_correlation_id,outcome,created_at) VALUES('fixture-admin','admin','sermon.update','sermon',$1,'[\"title\",\"slug\"]','anonymous-composite-edit','succeeded','2020-01-01')",[ids[0]]);
  repository=await build();expect((await repository.findPublishedBySlug('final-composite-fixture'))?.title).toBe('Explicit anonymous title');expect(await repository.findPublicPathDisposition(page.path)).toEqual({kind:'redirect',location:'/sermons/final-composite-fixture/'});
  await client.query("INSERT INTO redirects(old_path,new_path,status_code,reason,source_sermon_id) VALUES($1,'/sermons/final-composite-fixture/',301,'sermon_slug_changed',$2)",[page.path,ids[0]]);expect(await readSourcePublicPages(client)).toEqual([]);repository=await build();expect((await repository.findPublishedBySlug('final-composite-fixture'))?.sourcePublic?.content).toEqual(page.content);expect(await repository.findPublicPathDisposition(page.path)).toEqual({kind:'redirect',location:'/sermons/final-composite-fixture/'});await client.query('DELETE FROM redirects WHERE old_path=$1',[page.path]);
  const beforeAuthorization=await sourceRuntimeFingerprint(client);
  await client.query("INSERT INTO audit_events(actor_subject,actor_role,action,entity_type,entity_id,changed_fields,request_correlation_id,outcome) VALUES('anonymous-system','system','sermon.restricted.acceptance_changed','sermon',$1,'[]','anonymous-cache-authorization','succeeded')",[ids[0]]);
  expect(await sourceRuntimeFingerprint(client)).not.toBe(beforeAuthorization);
  const fingerprint=await sourceRuntimeFingerprint(client);await client.query("UPDATE sermon_question_answers SET status='draft' WHERE sermon_id=$1 AND display_order=1",[ids[0]]);expect(await sourceRuntimeFingerprint(client)).not.toBe(fingerprint);repository=await build();expect((await repository.findPublishedBySlug('original-composite-fixture'))?.summary).toBeNull();expect(await repository.findPublishedBySlug('final-composite-fixture')).toBeNull();
  await client.query("UPDATE sermon_question_answers SET status='approved' WHERE sermon_id=$1",[ids[0]]);await client.query('UPDATE source_public_routes SET withdrawn=true WHERE path=$1',[page.path]);repository=await build();expect(await repository.findPublishedBySlug('final-composite-fixture')).toBeNull();expect(await repository.findPublishedBySlug('original-composite-fixture')).toBeNull();expect(await repository.findPublishedBySlug('new-composite-fixture')).not.toBeNull();
  await client.query('UPDATE source_public_routes SET withdrawn=false WHERE path=$1',[page.path]);await client.query("INSERT INTO redirects(old_path,status_code,reason) VALUES($1,410,'anonymous_explicit_withdrawal')",[page.path]);repository=await build();expect(await repository.findPublishedBySlug('final-composite-fixture')).toBeNull();expect(await repository.findPublicPathDisposition(page.path)).toEqual({kind:'gone'});expect((await repository.listPublishedSitemapEntries()).some(item=>item.slug==='final-composite-fixture')).toBe(false);
 }finally{await client.query('ROLLBACK');client.release();}});
 it('source-public additive migration independently rolls back, reapplies and retains required indexes/triggers',async()=>{guard();const pool=getPool(),migration=await loadSourcePublicMigration();try{await pool.query(migration.upBody);expect((await pool.query("SELECT count(*)::int n FROM information_schema.tables WHERE table_name IN('source_public_versions','source_public_routes','source_public_imports')")).rows[0].n).toBe(3);await pool.query(migration.downBody);await pool.query(migration.upBody);expect((await pool.query("SELECT count(*)::int n FROM pg_trigger WHERE tgname IN('source_public_versions_immutable','source_public_imports_immutable')")).rows[0].n).toBe(2);expect((await pool.query("SELECT count(*)::int n FROM pg_indexes WHERE indexname='source_public_wordpress_idx'")).rows[0].n).toBe(1);}finally{await pool.query(migration.downBody);}});
 it('source-public import, no-clobber delta and scoped restoration preserve original dates and all sermon review state',async()=>{guard();const pool=getPool(),client=await pool.connect();try{await client.query('BEGIN');const suffix=[...(await completedSchemaMigrations()).slice(22),await loadAcceptedSemanticMigration(),await loadCmsMigration()];for(const item of suffix){await client.query(item.upBody);await client.query('INSERT INTO schema_migrations(migration_order,migration_id,checksum_sha256) VALUES($1,$2,$3)',[item.order,item.id,item.checksumSha256]);}
 const before=(await client.query("SELECT md5(coalesce(json_agg(to_jsonb(s) ORDER BY id)::text,'[]')) hash FROM sermons s")).rows;
 expect(await applySourcePublicMigration(client)).toBe('applied');expect(await applySourcePublicMigration(client)).toBe('unchanged');expect(await verifyCmsSchema(client)).toBe(28);
 const page=fixture(),bundle=sourceBundleSchema.parse({format:'sgbc-source-public-v1',capturedAt:'2026-10-09T00:00:00Z',inventorySha256:hash,pages:[page],expectedVersions:{[page.path]:null}});
 const initial=await importSourcePublicBundle(client,bundle,commit);expect(initial.inserted).toBe(1);expect((await importSourcePublicBundle(client,bundle,commit)).unchanged).toBe(1);expect((await readSourcePublicPages(client))[0]?.publishedAt).toBe('2004-01-01T00:00:00Z');
 await client.query('SAVEPOINT conflict');await expect(importSourcePublicBundle(client,{...bundle,pages:[{...page,title:'An observed source delta'}]},commit)).rejects.toThrow('concurrent_change');await client.query('ROLLBACK TO SAVEPOINT conflict');
 const delta={...bundle,pages:[{...page,title:'An observed source delta'}],expectedVersions:{[page.path]:sourceVersionHash(page)}};const changed=await importSourcePublicBundle(client,delta,commit);expect(changed.updated).toBe(1);
 await client.query('SAVEPOINT recovery');await expect(restoreSourcePublicImport(client,initial.bundleSha256,commit)).rejects.toThrow('later_change');await client.query('ROLLBACK TO SAVEPOINT recovery');expect((await restoreSourcePublicImport(client,changed.bundleSha256,commit)).restored).toBe(1);expect((await readSourcePublicPages(client))[0]?.title).toBe(page.title);
 await client.query('SAVEPOINT immutable');await expect(client.query('UPDATE source_public_versions SET payload=payload')).rejects.toThrow('immutable');await client.query('ROLLBACK TO SAVEPOINT immutable');
 const migration=await loadSourcePublicMigration();await client.query('SAVEPOINT down');await expect(client.query(migration.downBody)).rejects.toThrow('Preserve source migration history');await client.query('ROLLBACK TO SAVEPOINT down');
 expect((await client.query("SELECT md5(coalesce(json_agg(to_jsonb(s) ORDER BY id)::text,'[]')) hash FROM sermons s")).rows).toEqual(before);
 expect((await restoreSourcePublicImport(client,initial.bundleSha256,commit)).restored).toBe(1);expect(await readSourcePublicPages(client)).toEqual([]);await expect(importSourcePublicBundle(client,bundle,commit)).rejects.toThrow('explicit_withdrawal');
 await sourceCmsPostgresLifecycle(client);
 }finally{await client.query('ROLLBACK');client.release();}});
}
