import{createHash}from"node:crypto";import{readFile,writeFile}from"node:fs/promises";import{isAbsolute}from"node:path";import{Pool,type PoolClient}from"pg";
import{protectedLocalPostgresPassword,protectedLocalPostgresUser}from"../src/migration/protected-local-postgres";
import{canonicalReviewJson}from"../src/domain/delegated-ai-review";import{d161SourceManifest}from"../src/domain/d161-review";
import{stagingConfiguration,stagingPassword,verifyStagingIdentity}from"../src/staging/guard";import{verifyReleaseSchema}from"../src/staging/database-verification";
const tables=["delegated_ai_review_scopes","remaining_ai_review_scopes","delegated_ai_review_members","remaining_ai_review_members","sermon_ai_content_reviews","sermon_ai_metadata_assignments","sermon_ai_component_reviews","sermon_d161_restricted_acceptances","audit_events"]as const;
let diagnosticStage="entry";
type Packet={schemaVersion:1,manifestSha256:string,exportedAt:string,sermonIds:string[],speakerUpdates:any[],tables:Record<string,{primaryKey:string[],rows:any[]}>,packageSha256:string};
const plain=(v:unknown):unknown=>v instanceof Date?v.toISOString():Array.isArray(v)?v.map(plain):v&&typeof v==="object"?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,plain(x)])):v;
const hash=(v:unknown)=>createHash("sha256").update(canonicalReviewJson(plain(v))).digest("hex");const packetHash=(p:Packet)=>hash({...p,packageSha256:""});
const name=(v:string)=>{if(!/^[a-z][a-z0-9_]*$/u.test(v))throw new Error("d161_sync_identifier_refused");return`"${v}"`;};
async function pk(c:PoolClient,table:string){return(await c.query(`SELECT a.attname column_name FROM pg_index i JOIN pg_attribute a ON a.attrelid=i.indrelid AND a.attnum=ANY(i.indkey) WHERE i.indrelid=('public.'||$1)::regclass AND i.indisprimary ORDER BY array_position(i.indkey,a.attnum)`,[table])).rows.map(r=>String(r.column_name));}
async function rows(c:PoolClient,table:string,ids:string[]){const primaryKey=await pk(c,table);let sql=`SELECT to_jsonb(t) row FROM ${name(table)} t `,args:any[]=[];
  if(table.endsWith("_scopes"))sql+="WHERE id='D-161' ";else if(table.endsWith("_members")||table.startsWith("sermon_ai_"))sql+="WHERE scope_id='D-161' ";else if(table==="sermon_d161_restricted_acceptances"){sql+="WHERE source_manifest_sha256=$1 ";args=[d161SourceManifest];}else{sql+="WHERE actor_subject='codex-d161-d160-private-review' AND entity_id=ANY($1::uuid[]) ";args=[ids];}
  sql+=`ORDER BY ${primaryKey.map(name).join(",")}`;return{primaryKey,rows:(await c.query(sql,args)).rows.map(r=>r.row)};}
async function insert(c:PoolClient,table:string,p:{primaryKey:string[],rows:any[]},row:any){const where=p.primaryKey.map((k,i)=>`${name(k)}=$${i+1}`).join(" AND "),values=p.primaryKey.map(k=>row[k]);const prior=(await c.query(`SELECT to_jsonb(t) row FROM ${name(table)} t WHERE ${where}`,values)).rows[0]?.row;if(prior){if(hash(prior)!==hash(row))throw new Error("d161_sync_conflict");return"unchanged";}
  const columns=(await c.query("SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1 AND is_generated='NEVER' AND identity_generation IS NULL ORDER BY ordinal_position",[table])).rows.map(r=>String(r.column_name));const cols=columns.map(name).join(",");await c.query(`WITH x AS(SELECT * FROM jsonb_populate_record(NULL::${name(table)},$1::jsonb)) INSERT INTO ${name(table)}(${cols}) SELECT ${cols} FROM x`,[JSON.stringify(row)]);return"inserted";}
async function exportLocal(){const out=process.env.D161_SYNC_PACKAGE;if(!out||!isAbsolute(out)||!out.endsWith(".private.json"))throw new Error("d161_sync_configuration_refused");diagnosticStage="connect";const db=new Pool({host:"127.0.0.1",port:5432,database:"savinggrace_sermons_test",user:protectedLocalPostgresUser,password:protectedLocalPostgresPassword,max:1,options:"-c default_transaction_read_only=on -c timezone=UTC"});const c=await db.connect();try{await c.query("BEGIN READ ONLY");diagnosticStage="identity";const ok=(await c.query("SELECT current_database()='savinggrace_sermons_test' AND inet_server_addr()='127.0.0.1'::inet AND inet_server_port()=5432 ok")).rows[0]?.ok;if(!ok)throw new Error("d161_sync_source_refused");diagnosticStage="members";const members=(await c.query("SELECT sequence,sermon_id FROM remaining_ai_review_members WHERE scope_id='D-161' ORDER BY sequence")).rows;if(members.length!==36||members.some((r,i)=>r.sequence!==i+1))throw new Error("d161_sync_scope_refused");const ids=members.map(r=>r.sermon_id);diagnosticStage="counts";const counts=(await c.query(`SELECT (SELECT count(*) FROM sermon_ai_content_reviews WHERE scope_id='D-161') content,(SELECT count(*) FROM sermon_ai_component_reviews WHERE scope_id='D-161') components,(SELECT count(*) FROM sermon_ai_metadata_assignments WHERE scope_id='D-161') assignments,(SELECT count(*) FROM sermon_d161_restricted_acceptances) acceptances`)).rows[0];if(Number(counts.content)!==288||Number(counts.components)!==220||Number(counts.assignments)!==5||Number(counts.acceptances)!==4)throw new Error("d161_sync_review_state_refused");diagnosticStage="speaker_updates";const speakerUpdates=(await c.query(`SELECT s.id,s.speaker_id,s.row_version,s.updated_at,s.updated_by_subject FROM sermons s JOIN sermon_ai_metadata_assignments a ON a.sermon_id=s.id AND a.scope_id='D-161' AND a.component='speaker' ORDER BY s.id`)).rows.map(r=>({...r,expectedBeforeVersion:r.row_version-1}));const packet:any={schemaVersion:1,manifestSha256:d161SourceManifest,exportedAt:new Date().toISOString(),sermonIds:ids,speakerUpdates,tables:{},packageSha256:""};for(const table of tables){diagnosticStage=`table_${table}`;packet.tables[table]=await rows(c,table,ids);}diagnosticStage="package_hash";packet.packageSha256=packetHash(packet);diagnosticStage="package_write";await writeFile(out,JSON.stringify(packet),{encoding:"utf8",flag:"wx",mode:0o600});await c.query("ROLLBACK");process.stdout.write(JSON.stringify({outcome:"exported",records:36,acceptances:4,packageSha256:packet.packageSha256,rows:Object.fromEntries(tables.map(t=>[t,packet.tables[t].rows.length]))})+"\n");}finally{c.release();await db.end();}}
async function importStaging(){if(process.env.ALLOW_STAGING_D161_SYNC!=="1")throw new Error("d161_sync_gate_required");const input=process.env.D161_SYNC_PACKAGE;if(!input||!isAbsolute(input))throw new Error("d161_sync_configuration_refused");const packet:Packet=JSON.parse(await readFile(input,"utf8"));if(packet.schemaVersion!==1||packet.manifestSha256!==d161SourceManifest||packet.sermonIds.length!==36||new Set(packet.sermonIds).size!==36||packet.packageSha256!==packetHash(packet))throw new Error("d161_sync_package_refused");const config=stagingConfiguration(process.env,true),db=new Pool({...config,password:stagingPassword(config.passwordFile),max:1});const c=await db.connect();try{await c.query("BEGIN ISOLATION LEVEL SERIALIZABLE");await verifyStagingIdentity(c,true);await verifyReleaseSchema(c,20);const sermons=(await c.query("SELECT count(*)::int n FROM sermons WHERE id=ANY($1::uuid[])",[packet.sermonIds])).rows[0]?.n;if(sermons!==36)throw new Error("d161_sync_target_scope_refused");let changed=0,unchanged=0;for(const u of packet.speakerUpdates){const s=(await c.query("SELECT speaker_id,row_version,updated_at,updated_by_subject FROM sermons WHERE id=$1 FOR UPDATE",[u.id])).rows[0];if(!s)throw new Error("d161_sync_speaker_target_missing");if(s.speaker_id===u.speaker_id&&s.row_version===u.row_version&&new Date(s.updated_at).toISOString()===new Date(u.updated_at).toISOString()&&s.updated_by_subject===u.updated_by_subject){unchanged++;continue;}if(s.speaker_id!==null||s.row_version!==u.expectedBeforeVersion)throw new Error("d161_sync_speaker_conflict");await c.query("UPDATE sermons SET speaker_id=$2,row_version=$3,updated_at=$4,updated_by_subject=$5 WHERE id=$1",[u.id,u.speaker_id,u.row_version,u.updated_at,u.updated_by_subject]);changed++;}
    for(const table of tables){const tablePacket=packet.tables[table];if(!tablePacket)throw new Error("d161_sync_table_missing");for(const row of tablePacket.rows){const v=await insert(c,table,tablePacket,row);if(v==="inserted")changed++;else unchanged++;}}const accepted=(await c.query("SELECT count(*)::int n FROM sermon_d161_restricted_acceptances")).rows[0]?.n;if(accepted!==4)throw new Error("d161_sync_acceptance_count_refused");await c.query("COMMIT");process.stdout.write(JSON.stringify({outcome:changed?"imported":"unchanged",changed,unchanged,acceptances:accepted,packageSha256:packet.packageSha256})+"\n");}catch(error){await c.query("ROLLBACK");throw error;}finally{c.release();await db.end();}}
async function main(){const operation=process.argv[2];if(operation==="export")await exportLocal();else if(operation==="import")await importStaging();else throw new Error("d161_sync_operation_refused");}
main().catch(error=>{const code=error instanceof Error&&/^d161_sync_[a-z_]+$/u.test(error.message)?error.message:"d161_sync_refused",providerCode=typeof(error as any)?.code==="string"&&/^[A-Z0-9_]{1,20}$/u.test((error as any).code)?(error as any).code:"unavailable";process.stderr.write(JSON.stringify({code,providerCode,stage:diagnosticStage})+"\n");process.exitCode=1;});
