import {cmsSearchAppearance} from './seo-preview';
import {renderVisualEditor,disposeVisualEditor} from './visual-editor';
export {disposeVisualEditor} from './visual-editor';
import type {CmsEntity,CmsRevision,CmsKind} from '../../cms/model';
import {escape,markupHtml,richTextValue,safeHref,titleCase,moduleNames,newModule,newBlock,newArrayItem,optionalFieldsFor,shouldShowField,type CmsObject,type CmsValue} from './fields';
import './style.css';
interface Asset {id:string;url:string;name?:string;originalFilename?:string;mimeType?:string;type?:string;size?:number;alt?:string}
interface Host {main:HTMLElement;announce:(message:string)=>void;onDirty:(dirty:boolean)=>void;navigate:(path:string)=>Promise<void>}
const base='/api/v1/admin/cms';
let csrf='';
const hidden=new Set(['id','kind','status','source','sourceIds','legacyPaths','legacyPath','notes','template']);
const richNames=new Set(['text','lede','paragraph','intro','quote','caption']);
const imageNames=new Set(['image','media','logoAsset','footerLogoAsset','faviconAsset','touchIconAsset']);
const fieldId=(path:string)=>'cms-'+path.replace(/[^a-z0-9-]/gi,'-');
const dateLabel=(value:string)=>new Intl.DateTimeFormat('en-AU',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
const contentTitle=(entity:CmsEntity)=>String(entity.draft.content.title??entity.draft.content.name??(entity.kind==='settings'?'Navigation & website settings':titleCase(entity.kind)));
function getAt(object:CmsObject,path:string):CmsValue {return path.split('.').reduce((value,key)=>(value as CmsObject)?.[key] as CmsValue,object as CmsValue);}
function setAt(object:CmsObject,path:string,value:CmsValue):void {const keys=path.split('.'),last=keys.pop()!;const parent=keys.reduce((current,key)=>(current as CmsObject)[key] as CmsValue,object as CmsValue);(parent as CmsObject)[last]=value;}
function clean(value:CmsValue):CmsValue {if(Array.isArray(value))return value.map(clean);if(value&&typeof value==='object'){const result:CmsObject={};for(const [key,item]of Object.entries(value)){if(item===''&&['media','email','cite','eyebrow','parent','page','tag','until'].includes(key))continue;result[key]=clean(item);}return result;}return value;}
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);if(init.body&&typeof init.body==='string')headers.set('content-type','application/json');if(!['GET','HEAD'].includes(init.method??'GET'))headers.set('x-csrf-token',csrf);const response=await fetch(base+path,{...init,headers});const data=await response.json().catch(()=>({}));if(!response.ok){if(response.status===401)throw Error('Your session has ended. Sign in again, then return to your saved draft.');const issues=data.error?.issues?.map((issue:{path?:string|Array<string|number>;message:string})=>`${(Array.isArray(issue.path)?issue.path:String(issue.path??'').split('.')).filter(part=>!['content','block'].includes(String(part))).map(part=>/^\d+$/.test(String(part))?'Item '+(Number(part)+1):titleCase(String(part))).join(' › ')}: ${/must match pattern|Invalid input: expected/i.test(issue.message)?'Enter a valid value for this field.':issue.message}`).join('\n');throw Error(response.status===409&&data.error?.code==='stale_write'?'Someone saved a newer version. Your changes are still here. Reload the saved version before trying again.':issues||data.error?.message||data.error?.code||'The request could not be completed. Please try again.');}return data as T;}
export async function renderCms(host:Host):Promise<void>{
 disposeVisualEditor();
 const session=await request<{csrfToken:string}>('/session');csrf=session.csrfToken;
 const [collection,assetResponse]=await Promise.all([request<{data:CmsEntity[]}>('/entities'),request<{data?:Asset[];assets?:Asset[]}>('/assets')]);
 const entities=collection.data,assets=assetResponse.data??assetResponse.assets??[];
 const id=location.pathname.match(/^\/admin\/cms\/entities\/([^/]+)$/)?.[1];
 if(id&&new URLSearchParams(location.search).get('view')!=='advanced'){const entity=entities.find(item=>item.id===id);if(!entity)throw Error('This content could not be found.');await renderVisualEditor(host,{entity,entities,assets,request});return;}
 host.main.classList.add('cms-workspace');
 host.main.innerHTML=`<nav class="cms-tabs" aria-label="Website management"><a href="/admin/cms" data-route${!location.pathname.endsWith('/assets')?' aria-current="page"':''}>Pages & content</a><a href="/admin/cms/assets" data-route${location.pathname.endsWith('/assets')?' aria-current="page"':''}>Images & documents</a><a href="/" target="_blank" rel="noopener">View website</a><button class="button" type="button" id="cms-sign-out">Sign out</button></nav><div id="cms-message" aria-live="polite"></div><div id="cms-content"></div>`;
 host.main.querySelector('#cms-sign-out')!.addEventListener('click',()=>{if(!window.confirm('Sign out of administration? Save any draft changes first.'))return;void request('/session',{method:'DELETE'}).then(()=>{host.onDirty(false);location.href='/admin/login';});});
 const region=host.main.querySelector<HTMLElement>('#cms-content')!;
 const message=(text:string,error=false)=>{const target=host.main.querySelector<HTMLElement>('#cms-message')!;target.className='cms-message'+(error?' cms-error':'');target.textContent=text;target.setAttribute('role',error?'alert':'status');};
 const busy=async(action:()=>Promise<void>)=>{const buttons=Array.from(region.querySelectorAll<HTMLButtonElement>('button[data-action]'));buttons.forEach(button=>button.disabled=true);try{await action();}catch(error){message(error instanceof Error?error.message:'Unable to complete this action.',true);}finally{buttons.forEach(button=>button.disabled=false);}};
 const assetUrl=(value:string)=>assets.find(asset=>asset.id===value||asset.url===value)?.url??(value.startsWith('/')?value:'');
 const imageOptions=(selected:string)=>`<option value="">Choose an image</option>${assets.filter(asset=>/image/i.test(asset.mimeType??asset.type??'')||/\.(?:png|jpe?g|webp|gif)$/i.test(asset.url)).map(asset=>`<option value="${escape(asset.id)}"${selected===asset.id?' selected':''}>${escape(asset.name??asset.originalFilename??asset.alt??asset.id)}</option>`).join('')}`;
 function chooseLink(target:(value:string)=>void,current=''){
  const dialog=document.createElement('dialog');dialog.className='cms-dialog';dialog.innerHTML=`<form method="dialog"><h2>Choose a destination</h2><label for="cms-link-page">Website page</label><select id="cms-link-page"><option value="">Choose a page</option>${entities.filter(entity=>['page','home','post','event'].includes(entity.kind)).map(entity=>`<option value="${escape(entity.published?.content.path??entity.draft.content.path??'/')}">${escape(contentTitle(entity))}${entity.publishedRevisionId?'':' (unpublished draft)'}</option>`).join('')}</select><label for="cms-link-document">Uploaded document</label><select id="cms-link-document"><option value="">Choose a document</option>${assets.filter(asset=>/pdf/.test(asset.mimeType??asset.type??'')).map(asset=>`<option value="${escape(asset.url)}">${escape(asset.name??asset.originalFilename??'Document')}</option>`).join('')}</select><label for="cms-link-address">Or enter a web, email or telephone link</label><input id="cms-link-address" type="text" value="${escape(current)}" placeholder="https://example.org/"><p class="cms-help">Use a complete HTTPS address for another website.</p><p id="cms-link-error" role="alert"></p><div class="cms-actions"><button class="button" value="cancel">Cancel</button><button class="button primary" value="choose">Use destination</button></div></form>`;
  document.body.append(dialog);const input=dialog.querySelector<HTMLInputElement>('#cms-link-address')!;dialog.querySelectorAll('select').forEach(select=>select.addEventListener('change',()=>{input.value=select.value;}));dialog.querySelector('form')!.addEventListener('submit',event=>{if((event as SubmitEvent).submitter?.getAttribute('value')!=='choose')return;event.preventDefault();if(!safeHref(input.value)){dialog.querySelector('#cms-link-error')!.textContent='Choose a page or enter a valid HTTPS, email or telephone destination.';return;}target(input.value);dialog.close();});dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();
 }
 async function upload(file:File,alt=''):Promise<Asset>{const result=await request<Asset|{asset:Asset}>('/assets/upload',{method:'POST',headers:{'content-type':file.type,'x-upload-filename':encodeURIComponent(file.name),'x-upload-alt':encodeURIComponent(alt)},body:file});const asset='asset'in result?result.asset:result;assets.push(asset);return asset;}
 function assetLibrary(){
  region.innerHTML=`<header class="page-heading"><div><h1>Images & documents</h1><p>Choose existing church images or upload a file to use on a page. Uploads are retained with your revisions.</p></div></header><form id="cms-upload" class="cms-upload"><h2>Upload a file</h2><div class="cms-form-grid"><label>Image or PDF<input type="file" name="file" accept="image/png,image/jpeg,image/webp,image/gif,application/pdf" required></label><label>Alternative text<input name="alt" type="text" maxlength="500"><span class="cms-help">Describe what an image communicates. Leave blank only for decoration.</span></label></div><button class="button primary" type="submit">Upload file</button><p class="cms-help">PNG, JPEG, WebP, GIF or PDF. Images up to 10 MB; PDFs up to 20 MB.</p></form><div class="cms-asset-grid">${assets.map(asset=>`<article class="cms-asset">${/image/.test(asset.mimeType??asset.type??'')?`<img src="${escape(asset.url)}" alt="${escape(asset.alt??'')}" loading="lazy">`:'<span class="cms-document-mark">PDF document</span>'}<h2>${escape(asset.name??asset.originalFilename??asset.alt??'Church image')}</h2><p>${escape(asset.alt??'')}</p><a href="${escape(asset.url)}" target="_blank" rel="noopener">View file</a></article>`).join('')}</div>`;
  region.querySelector<HTMLFormElement>('#cms-upload')!.addEventListener('submit',event=>{event.preventDefault();void busy(async()=>{const formData=new FormData(event.currentTarget as HTMLFormElement),file=formData.get('file');if(!(file instanceof File)||!file.size)throw Error('Choose a file to upload.');await upload(file,String(formData.get('alt')??''));assetLibrary();message('File uploaded. It is ready to attach to a page.');});});
 }
 function list(){
  const selected=new URLSearchParams(location.search).get('kind')??'all';
  region.innerHTML=`<header class="page-heading"><div><h1>Website content</h1><p>Edit a draft, preview it, then publish when it is ready. Your live website keeps its published version while you work.</p></div><button class="button primary" id="cms-new" type="button">Create content</button></header><div class="cms-filters"><label for="cms-search">Find content<input id="cms-search" type="search" placeholder="Search pages and gatherings"></label><label for="cms-kind">Show<select id="cms-kind"><option value="all">All content</option>${['home','page','post','event','venue','settings'].map(kind=>`<option value="${kind}"${selected===kind?' selected':''}>${kind==='home'?'Homepage':kind==='settings'?'Navigation & settings':titleCase(kind)+'s'}</option>`).join('')}</select></label></div><div class="cms-content-list" role="list">${entities.map(entity=>`<article role="listitem" data-kind="${entity.kind}" data-search="${escape(contentTitle(entity).toLowerCase())}" class="cms-content-row"><div><a href="/admin/cms/entities/${entity.id}" data-route class="cms-content-title">${escape(contentTitle(entity))}</a><p>${escape(entity.draft.content.path??(entity.kind==='home'?'/':titleCase(entity.kind)))}</p></div><span class="cms-state">${entity.publishedRevisionId?(entity.draftRevisionId===entity.publishedRevisionId?'Published':'Draft changes'):'Unpublished'}</span><span class="cms-row-date">${escape(dateLabel(entity.draft.createdAt))}</span></article>`).join('')}</div><p class="cms-empty" hidden>No content matches. Try another search.</p>`;
  const filter=()=>{const query=(region.querySelector<HTMLInputElement>('#cms-search')!.value).toLowerCase(),kind=region.querySelector<HTMLSelectElement>('#cms-kind')!.value;let count=0;region.querySelectorAll<HTMLElement>('[data-kind]').forEach(row=>{row.hidden=(kind!=='all'&&row.dataset.kind!==kind)||!row.dataset.search!.includes(query);if(!row.hidden)count++;});region.querySelector<HTMLElement>('.cms-empty')!.hidden=!!count;};region.querySelector('#cms-search')!.addEventListener('input',filter);region.querySelector('#cms-kind')!.addEventListener('change',filter);filter();region.querySelector('#cms-new')!.addEventListener('click',newContent);
 }
 function newContent(){
  region.innerHTML=`<header class="page-heading"><div><h1>Create content</h1><p>Start a private draft. It will appear on the website only after you publish.</p></div></header><form id="cms-create" class="cms-form"><label>Content type<select name="kind"><option value="page">Church page</option><option value="post">Blog post</option><option value="event">Gathering or event</option><option value="venue">Venue</option></select></label><label>Title<input name="title" required maxlength="240"></label><label>Page address<input name="path" placeholder="/new-page/"><span class="cms-help">Use lowercase words separated by hyphens.</span></label><div class="cms-actions"><a class="button" href="/admin/cms" data-route>Cancel</a><button class="button primary" type="submit">Create draft</button></div></form>`;
  region.querySelector<HTMLFormElement>('#cms-create')!.addEventListener('submit',event=>{event.preventDefault();void busy(async()=>{const form=new FormData(event.currentTarget as HTMLFormElement),kind=String(form.get('kind'))as CmsKind,title=String(form.get('title')),slug=title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'new-page',date=new Date().toISOString().slice(0,10),key=`${kind}:custom-${crypto.randomUUID()}`,stableId=`custom-${crypto.randomUUID()}`;const path=String(form.get('path')||`/${kind==='event'?'events/':kind==='post'?'blogs/':''}${slug}/`);let content:CmsObject;
    if(kind==='venue')content={id:stableId,name:title,address:'',locality:'',legacyPath:'/venue/'+slug+'/'};
    else if(kind==='event')content={id:stableId,title,path,schedule:{kind:'single',date},start:'10:00',end:'11:00',venue:String(entities.find(entity=>entity.kind==='venue')?.draft.content.id??'church'),description:[''],legacyPaths:[],sourceIds:[],status:'draft'};
    else if(kind==='post')content={id:stableId,title,path,date,description:'',modules:[newModule('paragraph')],status:'draft'};
    else content={id:stableId,title,path,description:'',status:'draft',section:'about',legacyPaths:[],modules:[newModule('paragraph')],asideModules:[],related:[]};
    const created=await request<CmsEntity>('/entities',{method:'POST',body:JSON.stringify({key,kind,content})});await host.navigate('/admin/cms/entities/'+created.id);
  });});
 }
 async function edit(entity:CmsEntity){
  let current=entity,content=structuredClone(entity.draft.content)as CmsObject,dirty=false,openModule:string|null=null;
  const updateDirty=(value=true)=>{const preview=region.querySelector('[data-seo-preview]');if(preview)preview.innerHTML=cmsSearchAppearance(content,current.kind);dirty=value;host.onDirty(value);const state=region.querySelector<HTMLElement>('[data-save-state]');if(state)state.textContent=value?'Unsaved changes':'All changes saved';};
  function bindFields(){
   region.querySelectorAll<HTMLButtonElement>('[data-format]').forEach(button=>button.addEventListener('mousedown',event=>event.preventDefault()));
   region.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>('[data-field]').forEach(input=>input.addEventListener(input.tagName==='SELECT'||input.type==='checkbox'?'change':'input',()=>{let value:CmsValue=input.type==='checkbox'?(input as HTMLInputElement).checked:input.type==='number'||input.dataset.number==='true'?Number(input.value):input.value;if(input.dataset.nullable==='true'&&!input.value)value=null;if(input.dataset.provider){try{const url=new URL(input.value);value=input.dataset.provider==='video'?(url.hostname==='youtu.be'?url.pathname.slice(1):url.searchParams.get('v')??input.value):url.searchParams.get('list')??input.value;}catch{value=input.value;}}setAt(content,input.dataset.field!,value);updateDirty();if(/^(modules|asideModules)\.\d+\.enabled$/.test(input.dataset.field!)){const state=input.closest('.cms-module')?.querySelector('.cms-module-state');if(state)state.textContent=value?'Visible':'Hidden';}if(input.matches('[data-image]')){const preview=region.querySelector<HTMLImageElement>(`[data-image-preview="${input.dataset.field}"]`);if(preview){preview.src=assetUrl(String(value));preview.hidden=!value;}}}));
   region.querySelectorAll<HTMLElement>('[data-rich]').forEach(editor=>{editor.addEventListener('input',()=>{setAt(content,editor.dataset.rich!,richTextValue(editor).trimEnd());updateDirty();});editor.addEventListener('paste',event=>{event.preventDefault();document.execCommand('insertText',false,(event as ClipboardEvent).clipboardData?.getData('text/plain')??'');});});
   region.querySelectorAll<HTMLButtonElement>('[data-format]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();const editor=region.querySelector<HTMLElement>(`[data-rich="${button.dataset.editor}"]`)!;editor.focus();if(button.dataset.format==='link'){const selection=window.getSelection(),range=selection?.rangeCount?selection.getRangeAt(0).cloneRange():null;chooseLink(href=>{editor.focus();if(range){const selection=window.getSelection();selection?.removeAllRanges();selection?.addRange(range);}document.execCommand('createLink',false,href);editor.dispatchEvent(new Event('input'));});}else{document.execCommand(button.dataset.format!);editor.dispatchEvent(new Event('input'));}}));
   region.querySelectorAll<HTMLButtonElement>('[data-choose-link]').forEach(button=>button.addEventListener('click',()=>chooseLink(value=>{setAt(content,button.dataset.chooseLink!,value);updateDirty();redrawFields(button.dataset.chooseLink!);},String(getAt(content,button.dataset.chooseLink!)??''))));
   region.querySelectorAll<HTMLButtonElement>('[data-array-action]').forEach(button=>button.addEventListener('click',()=>{const array=getAt(content,button.dataset.array!)as CmsValue[],index=Number(button.dataset.index),action=button.dataset.arrayAction;if(action==='up'&&index>0)[array[index-1],array[index]]=[array[index]!,array[index-1]!];else if(action==='down'&&index<array.length-1)[array[index+1],array[index]]=[array[index]!,array[index+1]!];else if(action==='remove')array.splice(index,1);else if(action==='add'){
     if(button.dataset.array!.endsWith('.blocks')){const dialog=document.createElement('dialog');dialog.className='cms-dialog cms-module-picker';dialog.innerHTML=`<form method="dialog"><h2>Add content to this group</h2><div class="cms-module-options">${Object.entries(moduleNames).filter(([kind])=>current.kind==='home'||!kind.startsWith('home-')).map(([kind,name])=>`<button class="button" value="${kind}">${escape(name)}</button>`).join('')}</div><button class="button" value="cancel">Cancel</button></form>`;document.body.append(dialog);dialog.addEventListener('close',()=>{if(dialog.returnValue&&dialog.returnValue!=='cancel'){array.push(newBlock(dialog.returnValue));updateDirty();redrawFields(button.dataset.array!+'.'+(array.length-1));}dialog.remove();});dialog.showModal();return;}
     array.push(newArrayItem(content,button.dataset.array!));
    }updateDirty();redrawFields(button.dataset.array!+(action==='add'?'.'+(array.length-1):''));}));
   region.querySelectorAll<HTMLButtonElement>('[data-optional-action]').forEach(button=>button.addEventListener('click',()=>{const objectPath=button.dataset.objectPath??'',object=(objectPath?getAt(content,objectPath):content)as CmsObject,key=button.dataset.optionalKey!,descriptor=optionalFieldsFor(object,objectPath,current.kind,content).find(item=>item.key===key);if(!descriptor)return;if(button.dataset.optionalAction==='add')object[key]=structuredClone(descriptor.value);else delete object[key];updateDirty();redrawFields(objectPath?objectPath+'.'+key:key);host.announce(titleCase(key)+(button.dataset.optionalAction==='add'?' added to':' removed from')+' this draft.');}));
   region.querySelectorAll<HTMLInputElement>('[data-inline-upload]').forEach(input=>input.addEventListener('change',()=>{const file=input.files?.[0];if(file)void busy(async()=>{const asset=await upload(file);setAt(content,input.dataset.inlineUpload!,asset.id);updateDirty();redrawFields(input.dataset.inlineUpload!);message('Image uploaded and selected. Save your draft to keep this change.');});}));
  }
  function redrawFields(path:string){const pageDetails=region.querySelector<HTMLDetailsElement>('.cms-page-details')?.open;draw();const details=region.querySelector<HTMLDetailsElement>('.cms-page-details');if(details&&pageDetails)details.open=true;const control=Array.from(region.querySelectorAll<HTMLElement>('[data-field],[data-rich]')).find(item=>(item.dataset.field??item.dataset.rich)==path||(item.dataset.field??item.dataset.rich)?.startsWith(path+'.'));control?.focus();}
  function field(key:string,value:CmsValue,path:string,contextKey=''):string{
   const label=titleCase(key),id=fieldId(path);
   if(hidden.has(key)&&!(key==='kind'&&contextKey==='schedule'))return '';
   if(Array.isArray(value)){
    if(key==='sermonIds')return `<div class="cms-field"><span>Selected sermons</span><p>${value.length} selected</p><button class="button" type="button" data-sermon-picker="${path}">Choose sermons</button></div>`;
    if(key==='related')return `<fieldset class="cms-fieldset"><legend>${label}</legend>${value.map((item,index)=>`${referenceSelect(key,String(item),path+'.'+index,'page')}<button type="button" class="button" data-array-action="remove" data-array="${path}" data-index="${index}">Remove page</button>`).join('')}<button type="button" class="button" data-array-action="add" data-array="${path}">Add page</button></fieldset>`;
    return `<fieldset class="cms-fieldset"><legend>${label}</legend><div class="cms-array">${value.map((item,index)=>`<div class="cms-array-item"><div class="cms-item-order"><strong>${label==='Items'?'Item':label} ${index+1}</strong><div><button type="button" class="button" data-array-action="up" data-array="${path}" data-index="${index}"${index===0?' disabled':''} aria-label="Move item ${index+1} up">Move up</button><button type="button" class="button" data-array-action="down" data-array="${path}" data-index="${index}"${index===value.length-1?' disabled':''} aria-label="Move item ${index+1} down">Move down</button><button type="button" class="button" data-array-action="remove" data-array="${path}" data-index="${index}">Remove</button></div></div>${typeof item==='object'&&item!==null?objectFields(item as CmsObject,path+'.'+index,key):field(['description','text'].includes(key)?'text':key,item,path+'.'+index,key)}</div>`).join('')}</div>${key==='socialPlatforms'&&value.length>=4?'':`<button type="button" class="button" data-array-action="add" data-array="${path}">Add ${key==='blocks'?'section':label==='Items'?'item':label.toLowerCase().replace(/s$/,'')}</button>`}</fieldset>`;
   }
   if(value&&typeof value==='object')return `<fieldset class="cms-fieldset"><legend>${label}</legend>${objectFields(value,path,key)}</fieldset>`;
   if(typeof value==='boolean')return `<label class="cms-check"><input type="checkbox" data-field="${path}"${value?' checked':''}>${label}</label>`;
   if(imageNames.has(key))return `<div class="cms-image-field"><label for="${id}">${label}</label><div class="cms-image-control"><img data-image-preview="${path}" src="${escape(assetUrl(String(value??'')))}" alt="Selected image preview"${value?'':' hidden'}><div><select id="${id}" data-field="${path}" data-image>${imageOptions(String(value??''))}</select><label class="cms-upload-label">Upload a replacement<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" data-inline-upload="${path}"></label><span class="cms-help">The previous image stays available in revision history.</span></div></div></div>`;
   if(['parent','page','venue','event'].includes(key))return referenceSelect(key,String(value??''),path,key==='venue'?'venue':key==='event'?'event':'page');
   if(key==='videoId'||key==='listId')return "<label class='cms-field'>"+label+" link<input type='url' data-field='"+path+"' data-provider='"+(key==='videoId'?'video':'playlist')+"' value='"+escape(value?(key==='videoId'?'https://www.youtube.com/watch?v=':'https://www.youtube.com/playlist?list=')+String(value):'')+"' placeholder='Paste the YouTube link'><span class='cms-help'>Use the recording or playlist address. The player loads only when a visitor chooses it.</span></label>";
   const choices:Record<string,Array<[string,string]>>={section:['home','about','teaching','ministries','events','resources','giving','contact','blog','sermons'].map(item=>[item,titleCase(item)]),level:[['2','Large heading'],['3','Medium heading'],['4','Small heading']],columns:[['2','Two'],['3','Three'],['4','Four']],size:[['full','Full width'],['inset','Inset'],['portrait','Portrait']],treatment:[['banner','Banner'],['aside','Alongside text']],order:[['DESC','Newest first'],['ASC','Oldest first']],weekday:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day,index)=>[String(index),day]),kind:[['single','One date'],['weekly','Every week'],['monthly-first','First weekday of the month']]};
   if(choices[key])return `<label class="cms-field" for="${id}">${label}<select id="${id}" data-field="${path}"${typeof value==='number'?' data-number="true"':''}>${choices[key]!.map(([option,text])=>`<option value="${option}"${String(value)===option?' selected':''}>${text}</option>`).join('')}</select></label>`;
   if(richNames.has(key)&&typeof value==='string')return `<div class="cms-rich-field"><label id="${id}-label">${label}</label><div class="cms-rich-toolbar" role="toolbar" aria-label="Format ${escape(label.toLowerCase())}"><button type="button" data-format="bold" data-editor="${path}" aria-label="Bold"><strong>B</strong></button><button type="button" data-format="italic" data-editor="${path}" aria-label="Italic"><em>I</em></button><button type="button" data-format="link" data-editor="${path}">Add link</button></div><div class="cms-rich-editor" contenteditable="true" role="textbox" aria-multiline="true" aria-labelledby="${id}-label" data-rich="${path}">${markupHtml(value)}</div></div>`;
   const type=typeof value==='number'?'number':key==='date'||['from','until'].includes(key)||contextKey==='exclusions'?'date':['start','end'].includes(key)?'time':key==='email'?'email':'text';
   const link=/href$|^href$|^url$/i.test(key);
   return `<div class="cms-field"><label for="${id}">${label}</label>${key==='description'?`<textarea id="${id}" rows="3" data-field="${path}">${escape(value)}</textarea>`:`<input id="${id}" type="${type}" data-field="${path}" value="${escape(value)}"${value===null?' data-nullable="true"':contextKey==='focalPoint'?' min="0" max="100" step="1"':''}>`}${link?`<button type="button" class="button cms-select-link" data-choose-link="${path}">Choose page or document</button>`:''}${key==='path'?'<span class="cms-help">Publishing a changed address creates a redirect from the previous address.</span>':''}</div>`;
  }
  function referenceSelect(key:string,value:string,path:string,kind:string){return `<label class="cms-field">${titleCase(key)}<select data-field="${path}"><option value="">Choose ${kind==='page'?'a page':'a '+kind}</option>${entities.filter(item=>item.kind===kind).map(item=>`<option value="${escape(item.draft.content.id)}"${String(item.draft.content.id)===value?' selected':''}>${escape(contentTitle(item))}</option>`).join('')}</select></label>`;}
  function objectFields(object:CmsObject,path='',contextKey=''):string{
   const fields=Object.entries(object).filter(([key])=>!['modules','asideModules'].includes(key)&&shouldShowField(key,path)).map(([key,value])=>field(key,value,path?path+'.'+key:key,contextKey)).join('');
   const optional=optionalFieldsFor(object,path,current.kind,content).filter(item=>!item.present||typeof item.value!=='boolean');
   return fields+(optional.length?`<fieldset class="cms-fieldset"><legend>Optional details</legend><p class="cms-help">Add or remove these details in your draft. Changes reach the website only after publication.</p><div class="cms-actions">${optional.map(item=>`<button type="button" class="button" data-optional-action="${item.present?'remove':'add'}" data-object-path="${path}" data-optional-key="${item.key}">${item.present?'Remove':'Add'} ${escape(item.key==='enabled'?'visibility control':item.key==='sub'?'indentation control':titleCase(item.key).toLowerCase())}</button>`).join('')}</div></fieldset>`:'');
  }
  function moduleList(key:string){const modules=(content[key]??[])as CmsObject[];return `<section class="cms-modules" aria-labelledby="${key}-title"><div class="cms-section-heading"><h2 id="${key}-title">${key==='modules'?'Page sections':'Side content'}</h2><button class="button" data-add-module="${key}" type="button">Add section</button></div>${!modules.length?'<p class="cms-empty">No sections yet. Add a supported section to start composing this page.</p>':''}${modules.map((module,index)=>{const block=module.block as CmsObject,title=String(block.heading??block.title??moduleNames[String(block.kind)]??'Section');return `<details class="cms-module" data-module-id="${module.id}"${openModule===module.id?' open':''}><summary><span class="cms-module-name">${escape(title)}<small>${escape(moduleNames[String(block.kind)]??String(block.kind))}</small></span><span class="cms-module-state">${module.enabled?'Visible':'Hidden'}</span></summary><div class="cms-module-controls"><label class="cms-check"><input type="checkbox" data-field="${key}.${index}.enabled"${module.enabled?' checked':''}>Show this section</label><div class="cms-actions"><button type="button" class="button" data-module-action="up" data-list="${key}" data-index="${index}"${index===0?' disabled':''}>Move up</button><button type="button" class="button" data-module-action="down" data-list="${key}" data-index="${index}"${index===modules.length-1?' disabled':''}>Move down</button><button type="button" class="button" data-module-action="duplicate" data-list="${key}" data-index="${index}">Duplicate</button><button type="button" class="button" data-module-action="remove" data-list="${key}" data-index="${index}">Remove section</button></div></div><div class="cms-module-fields">${objectFields(block,`${key}.${index}.block`)}</div></details>`;}).join('')}</section>`;}
  function draw(){
   region.innerHTML=`<header class="page-heading"><div><a href="/admin/cms" data-route>All website content</a> · <a href="/admin/cms/entities/${current.id}" data-route>Visual editor</a><h1>${escape(String(content.title??content.name??contentTitle(current)))}</h1><p><span class="cms-state">${current.publishedRevisionId?(current.draftRevisionId===current.publishedRevisionId?'Published':'Saved draft has unpublished changes'):'Unpublished'}</span> <span data-save-state>${dirty?'Unsaved changes':'All changes saved'}</span></p></div></header><div class="cms-editor-toolbar"><button class="button primary" type="button" data-action="save">Save draft</button><button class="button" type="button" data-action="preview">Preview draft</button><button class="button" type="button" data-action="publish">Publish saved draft</button><button class="button" type="button" data-action="history">Revision history</button>${current.publishedRevisionId&&!['home','settings','navigation'].includes(current.kind)?'<button class="button" type="button" data-action="unpublish">Unpublish</button>':''}</div><form class="cms-editor" id="cms-editor"><details class="cms-page-details"${!content.modules?' open':''}><summary>${current.kind==='settings'?'Navigation, footer & global content':'Page details & search appearance'}</summary><div class="cms-form-grid">${objectFields(content)}</div><div data-seo-preview>${cmsSearchAppearance(content,current.kind)}</div></details>${content.modules?moduleList('modules'):''}${content.asideModules?moduleList('asideModules'):''}</form>`;
   bindFields();region.querySelectorAll<HTMLDetailsElement>('.cms-module').forEach(details=>details.addEventListener('toggle',()=>{if(details.open)openModule=details.dataset.moduleId!;}));
   region.querySelectorAll<HTMLButtonElement>('[data-module-action]').forEach(button=>button.addEventListener('click',()=>{const modules=content[button.dataset.list!]as CmsObject[],index=Number(button.dataset.index),action=button.dataset.moduleAction;openModule=String(modules[index]!.id);if(action==='up'&&index>0)[modules[index-1],modules[index]]=[modules[index]!,modules[index-1]!];if(action==='down'&&index<modules.length-1)[modules[index+1],modules[index]]=[modules[index]!,modules[index+1]!];if(action==='duplicate'){const copy=structuredClone(modules[index]!);const renew=(value:CmsValue):void=>{if(value&&typeof value==='object'){if(!Array.isArray(value)&&'id'in value)value.id=crypto.randomUUID();Object.values(value).forEach(renew);}};renew(copy);copy.id=crypto.randomUUID();modules.splice(index+1,0,copy);openModule=String(copy.id);}if(action==='remove'){modules.splice(index,1);openModule=modules[Math.min(index,modules.length-1)]?String(modules[Math.min(index,modules.length-1)]!.id):null;}updateDirty();draw();const moved=region.querySelector<HTMLElement>(`[data-module-id="${openModule}"] summary`);(moved??region.querySelector<HTMLElement>(`[data-add-module="${button.dataset.list}"]`))?.focus();host.announce('Section '+(action==='duplicate'?'duplicated':action==='remove'?'removed':'moved')+'. Save your draft to keep the change.');}));
   region.querySelectorAll<HTMLButtonElement>('[data-add-module]').forEach(button=>button.addEventListener('click',()=>{const dialog=document.createElement('dialog');dialog.className='cms-dialog cms-module-picker';dialog.innerHTML=`<form method="dialog"><h2>Add a section</h2><p>Choose one of the website’s supported layouts.</p><div class="cms-module-options">${Object.entries(moduleNames).filter(([kind])=>current.kind==='home'||!kind.startsWith('home-')).map(([kind,name])=>`<button class="button" value="${kind}">${escape(name)}</button>`).join('')}</div><button class="button" value="cancel">Cancel</button></form>`;document.body.append(dialog);dialog.addEventListener('close',()=>{if(dialog.returnValue&&dialog.returnValue!=='cancel'){const module=newModule(dialog.returnValue),block=module.block as CmsObject;if(block.media==='')block.media=assets.find(asset=>/image/.test(asset.mimeType??asset.type??''))?.id??'';(content[button.dataset.addModule!]as CmsObject[]).push(module);openModule=String(module.id);updateDirty();draw();region.querySelector<HTMLElement>(`[data-module-id="${openModule}"] summary`)?.focus();}dialog.remove();});dialog.showModal();}));
   region.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(button=>button.addEventListener('click',()=>void busy(async()=>{const action=button.dataset.action;if(action==='save'){await save();region.querySelector<HTMLElement>('[data-action=save]')?.focus();message('Draft saved. Your published website has not changed.');}if(action==='preview'){const preview=window.open('about:blank','_blank');try{await save();if(preview){preview.opener=null;preview.location.href='/cms-preview'+String(current.draft.content.path??'/')+'?entity='+current.id+'&revision='+current.draftRevisionId;}message('Preview opened with the saved draft.');}catch(error){preview?.close();throw error;}}if(action==='publish'){if(dirty)throw Error('Save your draft before publishing.');current=await request<CmsEntity>('/entities/'+current.id+'/publish',{method:'POST',body:JSON.stringify({expectedRowVersion:current.rowVersion,revisionId:current.draftRevisionId})});draw();region.querySelector<HTMLElement>('[data-action=publish]')?.focus();message('Published. The website now uses this revision.');}if(action==='history')await historyPanel();if(action==='unpublish')unpublishDialog();})));
   region.querySelectorAll<HTMLButtonElement>('[data-sermon-picker]').forEach(button=>button.addEventListener('click',()=>void chooseSermons(button.dataset.sermonPicker!)));
   region.querySelector<HTMLSelectElement>('[data-field="schedule.kind"]')?.addEventListener('change',event=>{const kind=(event.target as HTMLSelectElement).value,date=new Date().toISOString().slice(0,10);content.schedule=kind==='single'?{kind,date}:{kind,weekday:0,from:date,exclusions:[],until:''};updateDirty();redrawFields('schedule.kind');});
  }
  async function save(){const submitted=JSON.stringify(clean(content));current=await request<CmsEntity>('/entities/'+current.id,{method:'PUT',body:JSON.stringify({expectedRowVersion:current.rowVersion,content:JSON.parse(submitted)})});if(JSON.stringify(clean(content))===submitted){content=structuredClone(current.draft.content)as CmsObject;updateDirty(false);}else updateDirty(true);draw();}
  async function historyPanel(){const history=await request<{data:CmsRevision[]}>('/entities/'+current.id+'/revisions');const dialog=document.createElement('dialog');dialog.className='cms-dialog cms-history';dialog.innerHTML=`<form method="dialog"><h2>Revision history</h2><p>Restoring creates a new draft. It does not replace the live version until you publish.</p><ol>${history.data.map(revision=>`<li><div><strong>Revision ${revision.revisionNumber}${revision.id===current.publishedRevisionId?' · Published':''}</strong><p>${escape(dateLabel(revision.createdAt))} · ${escape(revision.actor)}</p></div><button type="button" class="button" data-restore="${revision.id}">Restore as draft</button></li>`).join('')}</ol><button class="button" value="close">Close</button></form>`;document.body.append(dialog);dialog.querySelectorAll<HTMLButtonElement>('[data-restore]').forEach(button=>button.addEventListener('click',()=>{if(dirty&&!window.confirm('Restore this revision and discard your unsaved changes?'))return;void busy(async()=>{current=await request<CmsEntity>('/entities/'+current.id+'/restore',{method:'POST',body:JSON.stringify({expectedRowVersion:current.rowVersion,revisionId:button.dataset.restore})});content=structuredClone(current.draft.content)as CmsObject;updateDirty(false);dialog.close();draw();message('Previous revision restored as a new draft. Preview it before publishing.');});}));dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();}
  function unpublishDialog(){const dialog=document.createElement('dialog');dialog.className='cms-dialog';dialog.innerHTML='<form method="dialog"><h2>Unpublish this page?</h2><p>Choose what visitors should see at its current address.</p><label>Address behavior<select name="disposition"><option value="gone">Page is no longer available (410)</option><option value="redirect">Redirect to another published page</option></select></label><label>Redirect destination<input name="targetPath" placeholder="/another-page/"></label><div class="cms-actions"><button class="button" value="cancel">Cancel</button><button class="button danger" value="unpublish">Unpublish</button></div></form>';document.body.append(dialog);dialog.querySelector('form')!.addEventListener('submit',event=>{if((event as SubmitEvent).submitter?.getAttribute('value')!=='unpublish')return;event.preventDefault();void busy(async()=>{const form=new FormData(event.currentTarget as HTMLFormElement),disposition=form.get('disposition');current=await request<CmsEntity>('/entities/'+current.id+'/unpublish',{method:'POST',body:JSON.stringify({expectedRowVersion:current.rowVersion,disposition,...(disposition==='redirect'?{targetPath:form.get('targetPath')}:{})})});dialog.close();draw();message('Page unpublished. Its address now uses the selected response.');});});dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();}
  async function chooseSermons(path:string){const result=await request<{data:Array<{id:string;title:string}>}>('/sermons');const selection=new Set((getAt(content,path)??[])as string[]);const dialog=document.createElement('dialog');dialog.className='cms-dialog';dialog.innerHTML=`<form method="dialog"><h2>Select sermons</h2><p>Only sermons eligible for this website are available.</p><input type="search" placeholder="Find a sermon" aria-label="Find a sermon"><div class="cms-sermon-options">${result.data.map(sermon=>`<label class="cms-check" data-sermon-title="${escape(sermon.title.toLowerCase())}"><input type="checkbox" value="${sermon.id}"${selection.has(sermon.id)?' checked':''}>${escape(sermon.title)}</label>`).join('')}</div><div class="cms-actions"><button class="button" value="cancel">Cancel</button><button class="button primary" value="save">Use selected sermons</button></div></form>`;document.body.append(dialog);dialog.querySelector('input[type=search]')!.addEventListener('input',event=>{const query=(event.target as HTMLInputElement).value.toLowerCase();dialog.querySelectorAll<HTMLElement>('[data-sermon-title]').forEach(label=>label.hidden=!label.dataset.sermonTitle!.includes(query));});dialog.addEventListener('close',()=>{if(dialog.returnValue==='save'){setAt(content,path,Array.from(dialog.querySelectorAll<HTMLInputElement>('input[type=checkbox]:checked')).map(input=>input.value));updateDirty();draw();}dialog.remove();});dialog.showModal();}
  draw();
 }
 if(location.pathname.endsWith('/assets'))assetLibrary();else if(id){const entity=entities.find(item=>item.id===id);if(!entity)throw Error('This content could not be found. Return to the content list.');await edit(entity);}else list();
}
