/** Public church-copy-only design laboratory. No database or sermon data. */
import { createServer } from "node:http";
import { siteAssetResponse } from "../src/server/http/site-assets";
import { html, raw } from "../src/frontend/html";
import { welcomeCopy, servicesCopy, heroCopy, pillars, contactCopy } from "../src/frontend/content/home-content";
import { picture } from "../src/frontend/components/blocks";
import { churchLogo } from "../src/frontend/shell";

const fonts = `@font-face{font-family:'Bitstream Vera Sans';src:url('/brand/fonts/bitstream-vera-sans-regular.ttf') format('truetype');font-weight:400;font-display:swap}@font-face{font-family:'Bitstream Vera Sans';src:url('/brand/fonts/bitstream-vera-sans-bold.ttf') format('truetype');font-weight:700;font-display:swap}`;
const base = `${fonts}*{box-sizing:border-box}body{margin:0;font:18px/1.5 'Bitstream Vera Sans',sans-serif;color:#192e3e;background:#fff}a{color:inherit;text-underline-offset:4px}h1,h2,h3,p{margin:0}img{display:block;max-width:100%;height:auto}header,main,footer{margin:auto}header{display:flex;align-items:center;justify-content:space-between;gap:2rem;padding:22px 5vw}header img{width:126px}nav{display:flex;gap:26px;align-items:center;font-size:16px}nav a{text-decoration:none;padding:12px 0}.cta{display:inline-flex;align-items:center;justify-content:center;background:#183d50;color:white;text-decoration:none;padding:13px 24px;min-height:48px}h1{font-size:clamp(3rem,5.5vw,6rem);line-height:1.02;letter-spacing:-.025em}h2{font-size:clamp(2rem,3vw,3rem);line-height:1.1}p{max-width:66ch}section{padding:70px 5vw}.intro{display:grid;grid-template-columns:1fr 1.2fr;gap:6vw}.intro h2{max-width:18ch}.services{display:grid;grid-template-columns:1fr 1fr;gap:5vw}.services h3{font-size:26px;margin-bottom:16px}.services p{margin:18px 0}.links{display:grid;grid-template-columns:1fr 1fr;gap:1rem 5vw}.links a{display:flex;justify-content:space-between;align-items:center;padding:22px 0;border-bottom:1px solid #abb3b8;text-decoration:none;font-size:24px}footer{background:#183d50;color:#fff;padding:42px 5vw;display:flex;justify-content:space-between;gap:28px}footer a{display:block;min-height:44px}a:focus-visible{outline:3px solid #b24627;outline-offset:4px}@media(max-width:700px){header{padding:14px 20px;gap:1rem;align-items:start}header img{width:105px}nav{gap:8px 16px;flex-wrap:wrap;justify-content:end;font-size:15px}nav a:nth-child(n+4){display:none}section{padding:42px 22px}.intro,.services{grid-template-columns:1fr;gap:26px}.links{grid-template-columns:1fr}footer{flex-direction:column}}`;
const nav = html`<header><a href="/">${churchLogo()}</a><nav aria-label="Primary"><a href="/about/">About us</a><a href="/sermons/">Sermons</a><a href="/ministries/">Church life</a><a href="/events/">Events</a><a href="/contact/">Contact</a></nav></header>`;
const services = html`<section class="services"><div><h3>${servicesCopy.morning.title}</h3><p>${servicesCopy.morning.text}</p><a href="${servicesCopy.morning.href}">Plan your morning visit</a></div><div><h3>${servicesCopy.evening.title}</h3><p>${servicesCopy.evening.text}</p><a href="${servicesCopy.evening.href}">Explore the evening service</a></div></section>`;
const intro = html`<section class="intro"><h2>${welcomeCopy.heading}</h2><p>${welcomeCopy.paragraph}</p></section>`;
const links = html`<section class="links">${pillars.map(p => html`<a href="${p.href}">${p.title}<span aria-hidden="true">→</span></a>`)}</section>`;
const footer = html`<footer><div><strong>${contactCopy.name}</strong><p>${heroCopy.address}</p></div><div><a href="${contactCopy.telephoneHref}">${contactCopy.telephone}</a><a href="mailto:${contactCopy.emailAddress}">${contactCopy.emailAddress}</a></div></footer>`;

function concept(name: string) {
  const a = name === "a";
  const b = name === "b";
  const style = a ? `h1,h2,h3{font-family:'Bitstream Vera Sans',sans-serif;font-weight:600}header{border-bottom:1px solid #c5ced3}.invitation{background:#dbe8ec;display:grid;grid-template-columns:1.45fr 1fr;gap:5vw;padding-top:54px;padding-bottom:50px}.invitation h1{max-width:11ch}.invitation .visit{align-self:end;border-top:1px solid #94abb6;padding-top:24px}.visit strong{display:block;font-size:29px;margin-bottom:10px}.visit p{max-width:32ch;margin-bottom:24px}.panorama{width:100%;height:440px;object-fit:cover;object-position:center 53%}.services{background:#f0f4f4}.intro h2{font-size:48px}@media(max-width:700px){.invitation{grid-template-columns:1fr;gap:30px;padding:36px 22px}.invitation h1{font-size:70px}.panorama{height:280px}.intro h2{font-size:40px}}`
    : b ? `body{background:#fcfaf6;color:#322d25}h1,h2,h3{font-family:Georgia,serif;font-weight:500}header{padding-bottom:28px}header nav{gap:20px}.cta{background:#6d482f}.doorway{display:grid;grid-template-columns:1.2fr 1fr;gap:6vw;align-items:center;padding:30px 5vw 65px}.doorway h1{font-size:clamp(3.2rem,4.3vw,5rem);max-width:11ch;margin-bottom:24px}.doorway p{max-width:42ch;margin-bottom:24px}.doorway img{width:100%;height:560px;object-fit:cover;object-position:center}.visit-note{border-top:1px solid #b9afa0;margin-top:26px;padding-top:20px;font-size:17px}.intro{background:#eee7dc}.services{border-bottom:1px solid #b9afa0}footer{background:#3c332c}@media(max-width:700px){.doorway{grid-template-columns:1fr;padding:28px 22px}.doorway img{height:330px;object-position:center 30%}.doorway h1{font-size:49px}}`
    : `body{background:#f6f4f0;color:#282b28}header{flex-direction:column;gap:14px;border-bottom:1px solid #7e8279;padding:28px 5vw 16px}header img{width:112px}nav{gap:40px}h1,h2,h3{font-family:Georgia,serif;font-weight:500}.editorial{text-align:center;padding-top:45px;padding-bottom:30px}.editorial h1{font-size:clamp(2.7rem,4.4vw,4.8rem);max-width:17ch;margin:auto}.editorial p{margin:22px auto;max-width:58ch}.editorial-photo{width:90%;height:350px;margin:auto;object-fit:cover;object-position:center 58%}.programme{display:flex;justify-content:space-between;align-items:center;gap:30px;margin:0 5vw;padding:24px 0;border-bottom:1px solid #7e8279}.programme p{max-width:40ch;font-size:16px}.programme strong{font-size:22px}.cta{background:#354735}.intro{grid-template-columns:1fr 1.4fr}.intro h2{font-size:36px}.services{background:#e5e8df}footer{background:#354735}@media(max-width:700px){nav{gap:10px 22px;justify-content:center}.editorial-photo{height:230px}.programme{flex-direction:column;align-items:start;gap:18px}.intro{grid-template-columns:1fr}.editorial h1{font-size:44px}}`;
  const hero = a ? html`<section class="invitation"><h1>Saving Grace<br>Bible Church</h1><div class="visit"><strong>${heroCopy.serviceTime}</strong><p>${heroCopy.address}</p><a class="cta" href="${heroCopy.joinHref}">${heroCopy.join}</a></div></section>${picture("congregation",{className:"panorama",eager:true})}`
    : b ? html`<section class="doorway"><div><h1>Welcome to Saving Grace Bible Church</h1><p>${welcomeCopy.paragraph}</p><a class="cta" href="${heroCopy.joinHref}">${heroCopy.join}</a><div class="visit-note"><strong>${heroCopy.serviceTime}</strong><p>${heroCopy.address}</p></div></div>${picture("welcome-door",{eager:true})}</section>`
    : html`<section class="editorial"><h1>Saving Grace<br>Bible Church</h1><p>${welcomeCopy.paragraph}</p></section>${picture("congregation",{className:"editorial-photo",eager:true})}<div class="programme"><div><strong>${heroCopy.serviceTime}</strong><p>${heroCopy.address}</p></div><a class="cta" href="${heroCopy.joinHref}">${heroCopy.join}</a></div>`;
  return html`<!doctype html><html lang="en-AU"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Saving Grace — design concept ${name.toUpperCase()}</title><style>${raw(base+style)}</style></head><body>${nav}<main>${hero}${intro}${services}${links}</main>${footer}</body></html>`.toString();
}
const port=Number(process.env.DESIGN_CONCEPT_PORT??"4411");
if(!Number.isInteger(port)||port<1024||port>65535) throw new Error("invalid_concept_port");
createServer(async(req,res)=>{
  try {
    const url=new URL(req.url??"/",`http://127.0.0.1:${port}`);
    const asset=siteAssetResponse(new Request(url));
    if(asset){res.writeHead(asset.status,Object.fromEntries(asset.headers));res.end(Buffer.from(await asset.arrayBuffer()));return;}
    const key=url.pathname.match(/^\/concept-([abc])\/$/)?.[1];
    res.writeHead(key?200:404,{"Content-Type":"text/html;charset=utf-8","Cache-Control":"no-store","X-Robots-Tag":"noindex"});
    res.end(key?concept(key):"Concept routes: /concept-a/, /concept-b/, /concept-c/");
  }catch{res.writeHead(500);res.end("concept_render_failed");}
}).listen(port,"127.0.0.1",()=>console.log(JSON.stringify({status:"public_copy_concepts_ready",port})));
