/** Finish a private source snapshot with verified durable assets and guarded CAS versions. */
import {readFile,writeFile,mkdir,lstat,realpath} from 'node:fs/promises';
import {resolve,dirname,relative,join,isAbsolute} from 'node:path';
import {sourceBundleSchema,sourcePageSchema,sourceHosts,sha256,type SourcePublicPage} from '../src/seo/source-public-model';
import {createCmsLocalPool,verifyCmsLocalIdentity} from '../src/cms/local-database';
import type {SourceNode} from '../src/domain/source-content';
interface Asset {url:string;status:number;capturedAt:string;sha256:string;mime:string;byteCount:number;relativePath:string;validation:{valid:boolean}}
const extensions:Record<string,string>={'image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/gif':'gif','image/avif':'avif','image/svg+xml':'svg','image/x-icon':'ico','application/pdf':'pdf','application/msword':'doc','application/vnd.openxmlformats-officedocument.wordprocessingml.document':'docx','application/vnd.ms-excel':'xls','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'xlsx','application/vnd.ms-powerpoint':'ppt','application/vnd.openxmlformats-officedocument.presentationml.presentation':'pptx','application/rss+xml':'rss','application/atom+xml':'atom','text/calendar':'ics'};
async function privateFile(path:string){const absolute=resolve(path),stat=await lstat(absolute);if(!absolute.replaceAll('\\','/').split('/').includes('private')||!stat.isFile()||stat.isSymbolicLink()||await realpath(absolute)!==absolute)throw Error('source_bundle_private_input');return absolute;}
async function confined(root:string,path:string,expectedBytes:number){const absolute=resolve(root,path),stat=await lstat(absolute);if(!Number.isInteger(expectedBytes)||expectedBytes<1||expectedBytes>52428800||!stat.isFile()||stat.size!==expectedBytes||isAbsolute(path)||relative(root,absolute).startsWith('..')||stat.isSymbolicLink()||await realpath(absolute)!==absolute)throw Error('source_bundle_asset_path');return readFile(absolute);}
async function main(){
 const [input,manifest,output,storage]=process.argv.slice(2);if(!input||!manifest||!output||!storage||!resolve(output).replaceAll('\\','/').split('/').includes('private'))throw Error('source_bundle_arguments');
 const inputPath=await privateFile(input),manifestPath=await privateFile(manifest),assetRoot=dirname(manifestPath),bundle=sourceBundleSchema.parse(JSON.parse(await readFile(inputPath,'utf8')));
 const ledgerPath=join(assetRoot,'ledger.private.json'),ledgerBytes=await readFile(ledgerPath),assetManifest=JSON.parse(await readFile(manifestPath,'utf8')) as {sourceLedgerSha256:string;assets:Record<string,Asset>;sourceDerivedOriginals:Record<string,{originalUrl:string}>;feeds?:Record<string,Asset>};
 if(sha256(ledgerBytes)!==assetManifest.sourceLedgerSha256||sha256(ledgerBytes)!==bundle.inventorySha256)throw Error('source_bundle_inventory_changed');
 const storageRoot=await realpath(storage),directory=join(storageRoot,'source-public');await mkdir(directory,{recursive:true});if((await lstat(directory)).isSymbolicLink()||await realpath(directory)!==directory)throw Error('source_bundle_asset_root');
 const assets=new Map<string,SourcePublicPage>(),files=new Map<string,{path:string;bytes:number;sha256:string}>(),refusals:Array<{url:string;reason:string}>=[];
 const candidates=[...Object.entries(assetManifest.assets),...Object.entries(assetManifest.feeds??{})];
 for(const [url,entry]of candidates.sort(([a],[b])=>Number(new URL(b).hostname==='www.savinggrace.org.au')-Number(new URL(a).hostname==='www.savinggrace.org.au'))){
  if(!entry||entry.status!==200||!entry.validation?.valid)continue;
  const u=new URL(url),ext=extensions[entry.mime];if(!sourceHosts.has(u.hostname)||!ext){refusals.push({url,reason:'asset_route_or_type_unsupported'});continue;}
  const bytes=await confined(assetRoot,entry.relativePath,entry.byteCount);if(sha256(bytes)!==entry.sha256||bytes.length!==entry.byteCount)throw Error('source_bundle_asset_integrity');
  const key=entry.sha256+'.'+ext,copy=join(directory,key),stat=await lstat(copy).catch(()=>null);if(stat&&(!stat.isFile()||stat.isSymbolicLink()||await realpath(copy)!==copy||stat.size!==bytes.length))throw Error('source_bundle_asset_file');const existing=stat?await readFile(copy):null;if(existing&&!existing.equals(bytes))throw Error('source_bundle_asset_collision');if(!existing)await writeFile(copy,bytes,{flag:'wx',mode:0o600});
  const page=sourcePageSchema.parse({path:u.pathname+u.search,kind:'asset',sourceUrl:url,sourceId:null,capturedAt:entry.capturedAt,responseSha256:entry.sha256,title:'Original public resource',heading:'Original public resource',description:null,indexable:false,canonicalSource:null,publishedAt:null,modifiedAt:null,content:[],sermon:null,asset:{storageKey:key,sha256:entry.sha256,contentType:entry.mime,bytes:bytes.length}});
  const prior=assets.get(page.path);if(prior&&prior.responseSha256!==page.responseSha256){if(['application/rss+xml','application/atom+xml','text/calendar'].includes(entry.mime)&&new URL(prior.sourceUrl).hostname==='www.savinggrace.org.au'&&u.hostname==='savinggrace.org.au'){refusals.push({url,reason:'canonical_host_dynamic_resource_diff_requires_review'});continue;}throw Error('source_bundle_asset_host_conflict');}assets.set(page.path,page);files.set(key,{path:copy,bytes:bytes.length,sha256:entry.sha256});
 }
 const replaced=new Set<string>();const imageMap=new Map(Object.entries(assetManifest.sourceDerivedOriginals??{}).flatMap(([url,value])=>{const path=new URL(value.originalUrl).pathname;return assets.has(path)?[[url,path] as const]:[]}));
 const rewrite=(nodes:SourceNode[]):SourceNode[]=>nodes.map(node=>{const copy={...node};if(node.src&&imageMap.has(node.src)){copy.src=imageMap.get(node.src)!;replaced.add(node.src);}if(node.children)copy.children=rewrite(node.children);return copy;});
 bundle.pages=bundle.pages.filter(p=>!assets.has(p.path)).map(page=>({...page,content:rewrite(page.content)})).concat([...assets.values()]);bundle.expectedVersions=Object.fromEntries(bundle.pages.map(p=>[p.path,null]));sourceBundleSchema.parse(bundle);
 await mkdir(dirname(resolve(output)),{recursive:true});await writeFile(output,JSON.stringify(bundle),{flag:'wx',mode:0o600});
 const pool=await createCmsLocalPool(true);try{await verifyCmsLocalIdentity(pool);const rows=(await pool.query<{path:string;version_sha256:string;withdrawn:boolean}>('SELECT path,version_sha256,withdrawn FROM source_public_routes')).rows,map=new Map(rows.map(r=>[r.path,r]));if(bundle.pages.some(p=>map.get(p.path)?.withdrawn))throw Error('source_bundle_explicit_withdrawal');const local={...bundle,expectedVersions:Object.fromEntries(bundle.pages.map(p=>[p.path,map.get(p.path)?.version_sha256??null]))};await writeFile(output+'.local.private.json',JSON.stringify(local),{flag:'wx',mode:0o600});}finally{await pool.end();}
 await writeFile(output+'.assets.private.json',JSON.stringify({files:Object.fromEntries(files),refusals,changedExternalImageReferences:[...replaced],sourceAssetManifestSha256:sha256(await readFile(manifestPath))}),{flag:'wx',mode:0o600});
 console.log(JSON.stringify({outcome:'source_bundle_completed',pages:bundle.pages.length,sermons:bundle.pages.filter(p=>p.kind==='sermon').length,assetRoutes:assets.size,uniqueFiles:files.size,rewrittenImageReferences:replaced.size,refused:refusals.length}));
}
main().catch(error=>{const message=error instanceof Error?error.message:'';console.error(JSON.stringify({outcome:'source_bundle_completion_refused',code:/^source_bundle_[a-z_]+$/u.test(message)?message:'source_bundle_schema_or_evidence'}));process.exitCode=1;});
