import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {dirname,resolve} from 'node:path';
import {sourceBundleSchema,sourcePathSchema,sha256,type SourcePublicPage} from '../src/seo/source-public-model';
import {deterministicSourceUuid} from '../src/migration/identity';
import {canonicalStoredSermonSlug} from '../src/domain/slug';
import {publicMediaSchema,type PublicMedia} from '../src/domain/sermon';
import {extractSourceStructuredData,type SourceSchemaCapture} from '../src/seo/source-structured-data';
interface Capture extends SourceSchemaCapture{url:string;status:number;capturedAt:string;bodySha256:string;title?:string;primaryHeading?:string;template?:string;sourcePostId?:number|null;mainFound?:boolean;contentTree?:SourcePublicPage['content'];eventMetadataTree?:SourcePublicPage['content'];language?:string;serviceDate?:string|null;publishedAt?:string|null;modifiedAt?:string|null;canonicalUrls?:string[];meta?:Record<string,string[]>;robots?:string[];links?:Array<{url?:string;href?:string}>;primaryMediaReferences?:Array<{url:string}>;taxonomyRelationships?:Array<{sourceClass:string;text:string;links:Array<{href:string;text:string}>}>;extractionWarning?:string|null;bodyLimitExceeded?:boolean;mainText?:string;responsePath?:string;}
function date(value:string|null|undefined):string|null{if(!value||Number.isNaN(Date.parse(value)))return null;return new Date(value).toISOString();}
function sourceMedia(record:Capture):PublicMedia[]{const result:PublicMedia[]=[];for(const item of record.primaryMediaReferences??[]){let u:URL;try{u=new URL(item.url);}catch{continue;}let media:PublicMedia|undefined;
 const host=u.hostname.toLowerCase().replace(/^www\./u,'');if(['youtube.com','youtube-nocookie.com','youtu.be'].includes(host)){const id=host==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')??/^\/embed\/([A-Za-z0-9_-]{11})$/u.exec(u.pathname)?.[1];if(id&&/^[A-Za-z0-9_-]{11}$/u.test(id))media={provider:'youtube',mediaType:'video',externalId:id,canonicalUrl:'https://www.youtube.com/watch?v='+id,title:'Sermon video'};}
 else if(host==='sermonaudio.com'||host.endsWith('.sermonaudio.com')){const id=u.searchParams.get('SID')??u.searchParams.get('sid')??/^\/player\/a\/(\d+)\/?$/u.exec(u.pathname)?.[1]??/^\/(?:sermons|embed\/sermon)\/(\d+)(?:\/|$)/u.exec(u.pathname)?.[1];if(id&&/^\d{1,24}$/u.test(id))media={provider:'sermonaudio',mediaType:'audio',externalId:id,canonicalUrl:'https://www.sermonaudio.com/sermons/'+id,title:'Sermon audio'};}
 if(media&&!result.some(r=>r.provider===media!.provider&&r.externalId===media!.externalId))result.push(publicMediaSchema.parse(media));}return result;}
function terms(record:Capture,key:string){const found=new Map<string,{name:string;slug:string}>();for(const group of record.taxonomyRelationships??[])for(const link of group.links){try{const slug=new URL(link.href).searchParams.get(key);if(slug)found.set(slug,{name:link.text,slug});}catch{}}return [...found.values()];}
function serviceDate(record:Capture):string|null{if(record.serviceDate&&/^\d{4}-\d{2}-\d{2}$/u.test(record.serviceDate))return record.serviceDate;const header=record.taxonomyRelationships?.find(r=>r.sourceClass==='sermon-header-details')?.text??'';const match=/^(\d{1,2}) (January|February|March|April|May|June|July|August|September|October|November|December),? (\d{4})/u.exec(header);if(!match)return null;const month=['January','February','March','April','May','June','July','August','September','October','November','December'].indexOf(match[2]!)+1;return `${match[3]}-${String(month).padStart(2,'0')}-${match[1]!.padStart(2,'0')}`;}
async function main(){const input=process.argv[2],output=process.argv[3];if(!input||!output||!output.replaceAll('\\','/').includes('/private/'))throw Error('source_bundle_private_output_required');const bytes=await readFile(input),ledger=JSON.parse(bytes.toString()) as {updatedAt:string;pages:Record<string,{recordPath:string;status:number;bodySha256:string}>};const pages:SourcePublicPage[]=[],held:Array<{url:string;reason:string}>=[],seen=new Set<string>();
 for(const [url,entry]of Object.entries(ledger.pages)){const u=new URL(url);if(entry.status!==200||u.hostname!=='www.savinggrace.org.au'||!sourcePathSchema.safeParse(u.pathname+u.search).success||u.pathname.endsWith('.xml')||u.pathname==='/robots.txt')continue;const record=JSON.parse(await readFile(resolve(dirname(input),entry.recordPath),'utf8')) as Capture;if(record.bodySha256!==entry.bodySha256||record.url!==url)throw Error('source_capture_integrity');if(!record.responsePath){held.push({url,reason:'source_empty_response_no_content'});continue;}if(!record.template||!record.mainFound){held.push({url,reason:'missing_main_content_extraction'});continue;}if(u.search&&!record.canonicalUrls?.includes(url)&&(record.template!=='archive'||u.pathname.startsWith('/sermons/')||[...u.searchParams.keys()].some(key=>['p','page_id','utm_source','utm_medium','utm_campaign'].includes(key))))continue;if(sha256(await readFile(resolve(dirname(input),record.responsePath)))!==entry.bodySha256)throw Error('source_capture_integrity');const routeKey=u.pathname+u.search;if(seen.has(routeKey))continue;seen.add(routeKey);if(!record.title||(!record.primaryHeading&&record.template==='sermon')){held.push({url,reason:'missing_title_or_primary_heading'});continue;}const heading=record.primaryHeading||record.title;
 const issues:string[]=[];if(record.bodyLimitExceeded)issues.push('source_body_limit');if(record.extractionWarning)issues.push(record.extractionWarning);const indexable=!(record.robots??[]).some(v=>/noindex|none/iu.test(v))&&!/noindex|none/iu.test(record.meta?.['x-robots-tag']?.join(' ')??'');
 const page:SourcePublicPage={path:routeKey,kind:record.template==='sermon'?'sermon':record.template==='post'?'post':record.template==='event'?'event':record.template==='archive'?'archive':'page',sourceUrl:url,sourceId:record.sourcePostId??null,capturedAt:date(record.capturedAt)!,responseSha256:record.bodySha256,title:record.title,heading,hasOriginalHeading:Boolean(record.primaryHeading),description:record.meta?.description?.[0]??null,...(['website','article'].includes(record.meta?.['og:type']?.[0]??'')?{socialType:record.meta!['og:type']![0] as 'website'|'article'}:{}),...(record.meta?.['og:title']?.[0]?{socialTitle:record.meta['og:title'][0]}:{}),...(record.meta?.['og:description']?.[0]?{socialDescription:record.meta['og:description'][0]}:{}),...(record.meta?.['og:image']?.[0]?{socialImageSource:record.meta['og:image'][0]}:{}),language:record.language??'en',indexable:indexable&&issues.length===0&&(!u.search||Boolean(record.canonicalUrls?.includes(url))),canonicalSource:record.canonicalUrls?.[0]??null,publishedAt:date(record.publishedAt),modifiedAt:date(record.modifiedAt),content:[...(record.contentTree??[]),...(record.eventMetadataTree??[])].filter(n=>n.tag!=='text'||n.text?.trim()),links:(record.links??[]).map(r=>r.url??r.href??'').filter(Boolean),mediaReferences:(record.primaryMediaReferences??[]).map(r=>r.url),sermon:null,issues,passageTerms:terms(record,'sermon_topics')};
 if(page.kind==='sermon'){const slug=canonicalStoredSermonSlug(u.pathname.split('/')[2]??''),preached=serviceDate(record),speakers=terms(record,'sermon_speaker');if(!slug||!preached||!record.sourcePostId||speakers.length>1){held.push({url,reason:!slug?'unsafe_slug':!preached?'missing_service_date':!record.sourcePostId?'missing_source_identity':'ambiguous_speaker'});continue;}const media=sourceMedia(record);page.language=/[\u0600-\u06ff]/u.test(heading)?'ar':page.language;page.sermon={id:deterministicSourceUuid('wp_posts',record.sourcePostId),title:heading,slug,serviceDate:preached,language:page.language.startsWith('ar')?'ar':'en',summary:null,speaker:speakers[0]??null,series:terms(record,'sermon_series'),scriptureReferences:terms(record,'sermon_topics').map(t=>({displayText:t.name,parseStatus:'unparsed'})),primaryPassages:[],primaryPassageState:'unresolved',books:terms(record,'sermon_book'),primaryMedia:media[0]??null,seoDescription:null,body:record.mainText||null,media,transcript:null,questionAnswers:[],relatedSermons:[]};}
 const schema=extractSourceStructuredData(record);if(schema.value)page.structuredData=schema.value;
 pages.push(page);
 }
 const bundle=sourceBundleSchema.parse({format:'sgbc-source-public-v1',capturedAt:date(ledger.updatedAt)!,inventorySha256:sha256(bytes),pages,expectedVersions:Object.fromEntries(pages.map(p=>[p.path,null]))});await mkdir(dirname(output),{recursive:true});await writeFile(output,JSON.stringify(bundle),{flag:'wx',mode:0o600});await writeFile(output+'.held.private.json',JSON.stringify(held),{flag:'wx',mode:0o600});console.log(JSON.stringify({outcome:'source_bundle_prepared',pages:pages.length,sermons:pages.filter(p=>p.kind==='sermon').length,held:held.length,inventorySha256:bundle.inventorySha256}));}
main().catch(error=>{console.error(JSON.stringify({outcome:'source_bundle_failed',code:error instanceof Error&&/^source_[a-z_]+$/u.test(error.message)?error.message:'source_schema_or_capture_failed'}));process.exitCode=1;});
